const referenceOnly = (id, title, url, educationalRole) => ({
  id,
  issuer: 'AQA',
  title,
  url,
  source_use_classification: 'REFERENCE_ONLY',
  educational_role: educationalRole,
  substantial_source_text_permitted_in_generation: false,
  derived_alignment_facts_permitted: true,
  checked_at: '2026-09-28',
  checker_method: 'fresh_official_aqa_web_verification',
})

export const aqaBusiness7132ExamTruthPreparation = {
  schema_version: 1,
  preparation_id: 'aqa-business-7132-2027-exam-truth-preparation-v1',
  authority_status: 'research_evidence_only',
  status: 'core_assessment_and_command_word_structure_prepared_pending_v07_and_question_family_denominator',
  course: {
    course_id: 'aqa:aqa-a-level:7132',
    awarding_body: 'AQA',
    qualification: 'A-level Business',
    specification_code: '7132',
    exam_year: 2027,
    specification_status: 'outgoing_current_for_2027_exams',
  },
  promotion_dependency: {
    required_subject_foundation_version: 'v0.7-aqa-7132-gap-reconciliation',
    required_subject_foundation_fingerprint: '64c072f188e3581a60787bd6a5556e4ac9ebf097434c6caf42a60d5598f61c53',
    required_targeted_reassurance_node_id: 'BUS-FIN-008',
    required_targeted_reassurance_decision: 'pass',
    promotion_before_dependency_pass_prohibited: true,
  },
  source_register: [
    referenceOnly('AQA-7132-SPEC', 'A-level Business 7132 specification', 'https://www.aqa.org.uk/subjects/business/a-level/business-7132/specification', 'Current specification identity and 2027 cohort applicability.'),
    referenceOnly('AQA-7132-AT-A-GLANCE', 'A-level Business 7132 specification at a glance', 'https://www.aqa.org.uk/subjects/business/a-level/business-7132/specification/specification-at-a-glance', 'Paper structure, duration, marks, weighting and question-format alignment facts.'),
    referenceOnly('AQA-7132-SCHEME', 'A-level Business 7132 scheme of assessment', 'https://www.aqa.org.uk/subjects/business/a-level/business-7132/specification/scheme-of-assessment', 'Qualification assessment rules, assessment objectives and weighting bands.'),
    referenceOnly('AQA-7132-QUANT', 'A-level Business 7132 quantitative skills annex', 'https://www.aqa.org.uk/subjects/business/a-level/business-7132/specification/annex-quantitative-skills-in-business', 'Quantitative-skills assessment requirement.'),
    referenceOnly('AQA-7132-DATES', 'A-level Business 7132 key dates', 'https://www.aqa.org.uk/subjects/business/a-level/business-7132/key-dates', '2027 examination dates and duration cross-check.'),
    referenceOnly('AQA-7132-COMMAND-WORDS', 'AQA AS and A-level Business command words', 'https://www.aqa.org.uk/resources/business/as-and-a-level/business-7131-7132/teach/command-words', 'Rights-safe structured response-demand meanings for common AQA Business command words; examples and model answers are excluded from downstream generation.'),
  ],
  qualification_rules: {
    linear_qualification: true,
    assessments_taken_at_end_of_course: true,
    all_exams_required_in_same_may_june_series: true,
    all_three_papers_compulsory: true,
    raw_mark_total: 300,
    scaled_mark_total: 300,
  },
  papers: [
    {
      exam_truth_id: 'ET-AQA-7132-P1',
      component_code: '7132/1',
      name: 'Business 1',
      duration_minutes: 120,
      raw_marks: 100,
      qualification_weight_percent: 33.3,
      content_scope: 'all_course_content',
      question_structure: {
        multiple_choice: { count: 15, marks: 15 },
        short_answer: { marks: 35 },
        essay_sections: [
          { section: 'C', marks: 25, choice: 'one_from_two' },
          { section: 'D', marks: 25, choice: 'one_from_two' },
        ],
      },
      ao_weighting_percent_ranges: { AO1: [9, 11], AO2: [9, 11], AO3: [5, 8], AO4: [5, 8] },
      exam_date_2027: '2027-05-13',
    },
    {
      exam_truth_id: 'ET-AQA-7132-P2',
      component_code: '7132/2',
      name: 'Business 2',
      duration_minutes: 120,
      raw_marks: 100,
      qualification_weight_percent: 33.3,
      content_scope: 'all_course_content',
      question_structure: {
        compulsory_data_response_questions: 3,
        approximate_marks_each: 33,
        part_questions_each: [3, 4],
      },
      ao_weighting_percent_ranges: { AO1: [6, 8], AO2: [8, 11], AO3: [8, 11], AO4: [6, 9] },
      exam_date_2027: '2027-05-19',
    },
    {
      exam_truth_id: 'ET-AQA-7132-P3',
      component_code: '7132/3',
      name: 'Business 3',
      duration_minutes: 120,
      raw_marks: 100,
      qualification_weight_percent: 33.3,
      content_scope: 'all_course_content',
      question_structure: {
        compulsory_case_studies: 1,
        approximate_follow_up_questions: 6,
      },
      ao_weighting_percent_ranges: { AO1: [5, 8], AO2: [5, 7], AO3: [9, 12], AO4: [9, 12] },
      exam_date_2027: '2027-06-08',
    },
  ],
  assessment_objectives: {
    AO1: { rights_safe_summary: 'knowledge and understanding of business terms, concepts, theories, methods and models', overall_weight_percent_range: [22, 25] },
    AO2: { rights_safe_summary: 'application of business knowledge and understanding to contexts', overall_weight_percent_range: [24, 27] },
    AO3: { rights_safe_summary: 'analysis of business issues and internal/external influences', overall_weight_percent_range: [25, 28] },
    AO4: { rights_safe_summary: 'evaluation of quantitative and qualitative information to reach evidence-based judgements or solutions', overall_weight_percent_range: [23, 26] },
  },
  command_word_alignment: {
    source_scope_note: 'AQA describes these as common rather than exhaustive; only rights-safe demand summaries are retained.',
    calculate: { demand: 'derive a numerical value; use appropriate method, accuracy and units where the question requires them', dominant_skill: 'quantitative_application' },
    describe: { demand: 'identify and state relevant characteristics, patterns or trends', dominant_skill: 'knowledge_application' },
    explain: { demand: 'give relevant reasons or purposes and develop how they address the question', dominant_skill: 'developed_explanation' },
    analyse: { demand: 'break the issue into relevant elements and develop contextual causal or logical relationships', dominant_skill: 'analysis' },
    evaluate: { demand: 'weigh relevant evidence and circumstances to reach a supported overall judgement', dominant_skill: 'evaluation' },
    justify: { demand: 'support a recommendation, view or conclusion with evidence while considering credible alternatives or weaknesses', dominant_skill: 'evaluation' },
    to_what_extent: { demand: 'judge the degree or significance of the stated factor relative to other relevant factors and support the conclusion', dominant_skill: 'evaluation' },
  },
  cross_paper_requirements: {
    synoptic_full_course_reasoning_required: true,
    extended_response_required: true,
    quantitative_skills_minimum_overall_percent: 10,
    quantitative_skills_may_be_assessed_across_assessment_objectives: true,
  },
  assessment_requirement_denominator: [
    { id: 'AR-7132-001', type: 'qualification_rule', fact: 'linear qualification; all compulsory exams completed in the same May/June series', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-002', type: 'paper_identity', fact: 'three compulsory papers, each 120 minutes and 100 raw marks', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-003', type: 'component_weighting', fact: 'each paper contributes approximately one third of the qualification', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-004', type: 'content_scope', fact: 'each paper may assess the full course content', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-005', type: 'paper_format', fact: 'Paper 1 combines multiple choice, short answer and two 25-mark essay responses selected from choices', mapped_exam_truth_ids: ['ET-AQA-7132-P1'] },
    { id: 'AR-7132-006', type: 'paper_format', fact: 'Paper 2 consists of three compulsory multi-part data-response questions', mapped_exam_truth_ids: ['ET-AQA-7132-P2'] },
    { id: 'AR-7132-007', type: 'paper_format', fact: 'Paper 3 uses one compulsory case study followed by approximately six questions', mapped_exam_truth_ids: ['ET-AQA-7132-P3'] },
    { id: 'AR-7132-008', type: 'assessment_objective', fact: 'AO1 knowledge/understanding is assessed within published component and overall weighting ranges', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-009', type: 'assessment_objective', fact: 'AO2 contextual application is assessed within published component and overall weighting ranges', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-010', type: 'assessment_objective', fact: 'AO3 analysis is assessed within published component and overall weighting ranges', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-011', type: 'assessment_objective', fact: 'AO4 evaluation/judgement is assessed within published component and overall weighting ranges', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-012', type: 'synoptic_demand', fact: 'assessment includes full-course integration and extended reasoning', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-013', type: 'quantitative_skills', fact: 'at least 10% of overall A-level marks assess relevant quantitative skills at a minimum of Level 2 mathematical demand', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
    { id: 'AR-7132-014', type: 'command_word_demand', fact: 'common AQA Business command words imply distinct descriptive, quantitative, explanatory, analytical and evaluative response demands; the published list is not exhaustive', mapped_exam_truth_ids: ['ET-AQA-7132-P1', 'ET-AQA-7132-P2', 'ET-AQA-7132-P3'] },
  ],
  remaining_before_exam_truth_promotion: [
    'Complete a rights-safe structured denominator for recurring question-family and marking-behaviour constraints from current official assessment resources without copying protected question or mark-scheme prose.',
    'Validate every assessment requirement against the exact current official source version and retain the extraction/verification record.',
    'Run the governed exact-course automated assurance after the v0.7 Subject Foundation dependency passes.',
  ],
}

export default aqaBusiness7132ExamTruthPreparation
