import { examSchema } from '../../../schema'

export const paper1Exam = examSchema.parse({
  id: 'aqa-a-level-7132-paper-1-sim-1',
  title: 'AQA A-level Business — Paper 1 Simulation 1',
  subtitle: 'Original Revision-authored AQA-aligned simulation',
  durationMinutes: 120,
  totalMarks: 100,
  caseHtml: `<p><strong>Original Revision simulation.</strong> This practice paper follows the AQA 7132 Paper 1 headline structure: Section A contains 15 one-mark multiple-choice questions, Section B contains 35 marks of short-answer work, and Sections C and D each contain a 25-mark essay choice. It is not an official AQA paper or mark scheme.</p>`,
  questions: [
    { id:'p1-q01', marks:1, topic:'business', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which formula calculates market capitalisation? A Revenue × profit margin  B Share price × issued shares  C Current assets ÷ current liabilities  D Fixed costs ÷ contribution', markingGuidance:['Correct answer: B — share price × number of issued shares.'] },
    { id:'p1-q02', marks:1, topic:'leadership', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which leadership style gives employees the greatest decision freedom? A Autocratic  B Paternalistic  C Democratic  D Laissez-faire', markingGuidance:['Correct answer: D — laissez-faire.'] },
    { id:'p1-q03', marks:1, topic:'marketing', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which is a behavioural segmentation variable? A Region  B Income  C Purchase frequency  D Age', markingGuidance:['Correct answer: C — purchase frequency.'] },
    { id:'p1-q04', marks:1, topic:'operations', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which is most associated with Just in Time operations? A Large safety inventory  B Minimal inventory and reliable replenishment  C Producing only luxury products  D High gearing', markingGuidance:['Correct answer: B.'] },
    { id:'p1-q05', marks:1, topic:'finance', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which is an internal source of finance? A Retained profit  B Bank loan  C Venture capital  D Overdraft', markingGuidance:['Correct answer: A — retained profit.'] },
    { id:'p1-q06', marks:1, topic:'hr', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which motivation theory distinguishes hygiene factors and motivators? A Taylor  B Maslow  C Herzberg  D Ansoff', markingGuidance:['Correct answer: C — Herzberg.'] },
    { id:'p1-q07', marks:1, topic:'strategic-position', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which is an external part of SWOT? A Strength  B Weakness  C Opportunity  D Core competence', markingGuidance:['Correct answer: C — opportunity.'] },
    { id:'p1-q08', marks:1, topic:'strategic-direction', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Existing products sold in new markets are classified by Ansoff as: A Market penetration  B Market development  C Product development  D Diversification', markingGuidance:['Correct answer: B — market development.'] },
    { id:'p1-q09', marks:1, topic:'strategic-methods', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — A merger between two businesses at the same stage of production is: A Backward vertical integration  B Forward vertical integration  C Horizontal integration  D Reshoring', markingGuidance:['Correct answer: C — horizontal integration.'] },
    { id:'p1-q10', marks:1, topic:'strategic-change', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which is one of Handy’s culture types? A Task  B Penetration  C Matrix pricing  D JIT', markingGuidance:['Correct answer: A — task culture.'] },
    { id:'p1-q11', marks:1, topic:'strategic-position', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which investment-appraisal method explicitly accounts for the time value of money? A Payback  B ARR  C NPV  D Break-even', markingGuidance:['Correct answer: C — net present value.'] },
    { id:'p1-q12', marks:1, topic:'strategic-position', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which is NOT one of Porter’s five forces? A Buyer power  B Supplier power  C Rivalry  D Employee engagement', markingGuidance:['Correct answer: D — employee engagement.'] },
    { id:'p1-q13', marks:1, topic:'strategic-change', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Strategic drift occurs when: A Strategy fails to keep pace with environmental change  B A firm always grows organically  C Current assets exceed current liabilities  D A project has positive NPV', markingGuidance:['Correct answer: A.'] },
    { id:'p1-q14', marks:1, topic:'strategic-methods', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — Which is explicitly an international market-entry method in 7132? A Licensing  B Delayering  C Job rotation  D Market mapping', markingGuidance:['Correct answer: A — licensing.'] },
    { id:'p1-q15', marks:1, topic:'strategic-change', assessmentObjectives:{ao1:1,ao2:0,ao3:0,ao4:0}, prompt:'Section A — The critical path is: A The cheapest project route  B The activity sequence determining minimum project duration  C Every activity with float  D The route with most employees', markingGuidance:['Correct answer: B.'] },

    { id:'p1-q16', marks:4, topic:'finance', assessmentObjectives:{ao1:1,ao2:3,ao3:0,ao4:0}, prompt:'Section B — A product sells for £40 and has variable cost of £24 per unit. Fixed costs are £192,000. Calculate the break-even output. Show your workings.', markingGuidance:['Contribution per unit = £40 − £24 = £16.','Break-even = £192,000 ÷ £16 = 12,000 units.','Award credit for correct method and final units according to the response produced; this is Revision guidance, not an official AQA mark scheme.'] },
    { id:'p1-q17', marks:4, topic:'strategic-position', assessmentObjectives:{ao1:1,ao2:3,ao3:0,ao4:0}, prompt:'Section B — A business has operating profit of £3.6m and capital employed of £24m. Calculate ROCE. Show your workings.', markingGuidance:['ROCE = operating profit ÷ capital employed × 100.','£3.6m ÷ £24m × 100 = 15%.'] },
    { id:'p1-q18', marks:4, topic:'leadership', assessmentObjectives:{ao1:1,ao2:3,ao3:0,ao4:0}, prompt:'Section B — A decision has a 60% chance of a £200,000 outcome and a 40% chance of a £50,000 outcome. The decision costs £90,000. Calculate the net gain.', markingGuidance:['Expected value = (0.6 × £200,000) + (0.4 × £50,000) = £140,000.','Net gain = £140,000 − £90,000 = £50,000.'] },
    { id:'p1-q19', marks:5, topic:'strategic-direction', assessmentObjectives:{ao1:1,ao2:3,ao3:1,ao4:0}, prompt:'Section B — A UK coffee chain plans to sell its existing products through stores in two countries where it has never operated. Explain why this strategy may be more risky than further market penetration in the UK.', markingGuidance:['Identify this as market development and compare with existing-products/existing-market penetration.','Develop unfamiliar market/customer/regulatory/competitive knowledge into a business consequence.','Do not claim market development is always unsuccessful; explain the source of additional uncertainty.'] },
    { id:'p1-q20', marks:6, topic:'strategic-methods', assessmentObjectives:{ao1:0,ao2:3,ao3:3,ao4:0}, prompt:'Section B — A rapidly growing online retailer has strong sales but increasingly pays suppliers late. Analyse how overtrading could threaten its performance.', markingGuidance:['Use the rapid growth and late-payment context.','Develop working-capital pressure: inventory/marketing/staff costs may be paid before customer cash is collected.','Push the chain into supplier relations, stock availability, finance cost or the ability to continue growing.'] },
    { id:'p1-q21', marks:6, topic:'strategic-change', assessmentObjectives:{ao1:0,ao2:2,ao3:1,ao4:3}, prompt:'Section B — A manufacturer must introduce new safety technology quickly, but experienced employees distrust management. Assess one reason why participation and involvement may or may not be the best way to overcome resistance.', markingGuidance:['Apply participation/involvement to employee knowledge, ownership and trust.','Counter with urgency, decision constraints or the possibility that consultation cannot resolve the underlying issue.','Reach a short contextual judgement about when participation is suitable.'] },
    { id:'p1-q22', marks:6, topic:'strategic-position', assessmentObjectives:{ao1:1,ao2:3,ao3:2,ao4:0}, prompt:'Section B — A business’s current ratio rises from 1.2:1 to 2.0:1 while its cash balance also rises. Analyse why the higher liquidity position is not automatically evidence of better overall performance.', markingGuidance:['Recognise improved apparent short-term liquidity.','Analyse possible inefficient working capital, excess inventory/receivables or foregone investment returns.','Use context: the value depends on business model, obligations and alternative uses of funds.'] },

    { id:'p1-q23', marks:25, topic:'strategic-direction', assessmentObjectives:{ao1:5,ao2:5,ao3:7,ao4:8}, prompt:'Section C — Choose ONE essay. A: “For a business seeking long-term growth, diversification is always a better strategy than market penetration.” To what extent do you agree? OR B: “A low-cost position is more sustainable than differentiation.” To what extent do you agree?', markingGuidance:['Answer only one option.','Use the relevant Ansoff or Porter concepts accurately and develop competing arguments.','Use realistic business contexts/examples as illustration, not invented evidence presented as fact.','Evaluate feasibility, risk, capabilities, competition and changing conditions.','Finish with a supported judgement that makes clear when the claim would and would not hold.'] },
    { id:'p1-q24', marks:25, topic:'strategic-change', assessmentObjectives:{ao1:5,ao2:5,ao3:7,ao4:8}, prompt:'Section D — Choose ONE essay. A: “Organisational culture is the most important factor determining whether strategic change succeeds.” To what extent do you agree? OR B: “Businesses should plan strategy in detail rather than allow strategy to emerge.” To what extent do you agree?', markingGuidance:['Answer only one option.','For A, compare culture with leadership, communication, structure, resources, urgency and external change.','For B, compare the value of planning with flexibility, learning, uncertainty and strategic drift.','Sustain analysis rather than listing models.','Finish with a clear, conditional judgement based on the type of organisation and environment.'] },
  ],
})

export const exams = [paper1Exam]
