import { examSchema } from '../../../schema'

export const lumenHotelsExam = examSchema.parse({
  id: 'lumen-hotels-1',
  title: 'Lumen Hotels Ltd',
  subtitle: 'Full original Paper 2 simulation — service business',
  durationMinutes: 90,
  totalMarks: 80,
  caseHtml: `<p>Lumen Hotels Ltd (LH) operates six boutique hotels in northern England. It is privately owned by two siblings. Revenue increased by 12% last year, but operating profit fell because wage, energy and food costs rose. Average room occupancy increased from 72% to 84%.</p><p>LH employs 310 people. Labour turnover among housekeeping and restaurant staff is 28%. Managers report that agency workers are increasingly used at weekends. Guest satisfaction remains high overall, but complaints about room-readiness times have increased.</p><p>The marketing director wants to introduce dynamic pricing and a loyalty programme. Research suggests business travellers are less price-sensitive on weekdays, while leisure customers are more price-sensitive outside holiday periods. A national chain has opened two new hotels in cities where LH operates.</p><p>The operations director proposes investing £900,000 in a central laundry facility and digital scheduling system. She expects lower unit costs and more consistent quality, but the project would require closing three local laundry teams. A bank will lend the full amount at a variable interest rate. The owners could instead sell 25% of the business to a private investor with hotel-sector experience.</p><p><strong>Data:</strong> 2025 revenue £18.0m; 2025 operating profit £1.44m. 2026 forecast revenue £20.2m; 2026 forecast operating profit before the proposed investment £1.31m.</p>`,
  questions: [
    { id: 'lh-q1', marks: 4, topic: 'finance', assessmentObjectives: { ao1: 2, ao2: 2, ao3: 0, ao4: 0 }, prompt: 'Calculate LH’s 2025 operating profit margin.', markingGuidance: ['Operating profit margin = operating profit ÷ revenue × 100.','£1.44m ÷ £18.0m × 100 = 8%.','Show method and %.'] },
    { id: 'lh-q2', marks: 4, topic: 'hr', assessmentObjectives: { ao1: 2, ao2: 2, ao3: 0, ao4: 0 }, prompt: 'Explain one likely consequence for LH of labour turnover of 28%.', markingGuidance: ['Use the hotel/service context.','Possible chain: frequent leavers → recruitment/training or agency use → higher cost/inconsistent service → guest satisfaction or profit affected.'] },
    { id: 'lh-q3', marks: 8, topic: 'marketing', assessmentObjectives: { ao1: 2, ao2: 3, ao3: 3, ao4: 0 }, prompt: 'Analyse one benefit to LH of introducing dynamic pricing.', markingGuidance: ['Recognise that prices can respond to demand/capacity conditions.','Use weekday business versus leisure price sensitivity and occupancy data.','Develop the chain into revenue, contribution, occupancy or positioning rather than merely saying prices rise.'] },
    { id: 'lh-q4', marks: 10, topic: 'operations', assessmentObjectives: { ao1: 3, ao2: 2, ao3: 5, ao4: 0 }, prompt: 'Analyse the possible impact on LH of centralising laundry operations.', markingGuidance: ['Develop benefits such as technology, consistency, better utilisation and lower unit cost.','Develop drawbacks such as disruption, transport, resilience and employee effects.','Apply to room-readiness complaints and current cost pressure.'] },
    { id: 'lh-q5', marks: 14, topic: 'leadership', assessmentObjectives: { ao1: 3, ao2: 3, ao3: 3, ao4: 5 }, prompt: 'Assess whether LH should use a more democratic leadership approach when implementing the proposed changes.', markingGuidance: ['Analyse employee knowledge/acceptance and the risk of resistance where jobs may close.','Counter with speed, consistency and management responsibility for a large investment.','Judgement should specify the degree of consultation rather than treating leadership styles as absolute.'] },
    { id: 'lh-q6', marks: 20, topic: 'finance', assessmentObjectives: { ao1: 5, ao2: 3, ao3: 5, ao4: 7 }, prompt: 'Should LH finance the £900,000 project with the bank loan or by selling 25% of the business? Justify your answer.', markingGuidance: ['Loan preserves ownership but exposes LH to repayments and variable interest-rate risk while profit is under pressure.','Equity reduces scheduled repayment pressure and may add sector expertise, but dilutes control/returns.','Use current margins, cost pressure and the owners’ objectives.','Reach a conditional judgement based on cash resilience, cost of finance and strategic value of the investor.'] },
    { id: 'lh-q7', marks: 20, topic: 'business', assessmentObjectives: { ao1: 4, ao2: 3, ao3: 4, ao4: 9 }, prompt: '“Improving employee retention is the most important action LH can take to improve long-term performance.” To what extent do you agree?', markingGuidance: ['Build the case for retention through agency cost, service quality, knowledge and implementation.','Compare with marketing, pricing, investment, competition and cost-control priorities.','Draw together HR, operations, finance and marketing.','Conclude which constraint is most important now and what could change that judgement.'] },
  ],
})

export const orbitFitnessExam = examSchema.parse({
  id: 'orbit-fitness-1',
  title: 'Orbit Fitness plc',
  subtitle: 'Full original Paper 2 simulation — national subscription service',
  durationMinutes: 90,
  totalMarks: 80,
  caseHtml: `<p>Orbit Fitness plc (OF) operates 54 gyms across the UK and sells monthly memberships through its app. Membership grew from 210,000 to 245,000 last year, but cancellations also increased after OF raised prices by 8%.</p><p>OF segments customers into value, standard and premium groups. Management wants to expand premium classes and personalised app coaching. Market research shows premium customers value convenience and specialist instruction, while the value segment is highly price-sensitive. Several low-cost competitors are opening new sites.</p><p>Each gym has considerable fixed costs. OF’s average monthly membership fee is £34. Average variable servicing cost is £6 per member per month. Head office fixed costs allocated across the business are £58m per year. Managers are considering closing eight lower-performing gyms and investing £12m in larger regional sites with more automation.</p><p>Employee engagement scores have fallen. Instructors say centrally set targets do not reflect local customer needs. The HR director proposes greater local decision authority and more performance-related pay. Trade-union representatives argue that targets could encourage unsafe workloads.</p><p><strong>Market index:</strong> UK commercial-gym memberships: 100 in 2024, 106 in 2025, 111 in 2026 forecast. OF membership index: 100 in 2024, 117 in 2025, 121 in 2026 forecast.</p>`,
  questions: [
    { id: 'of-q1', marks: 4, topic: 'business', assessmentObjectives: { ao1: 2, ao2: 2, ao3: 0, ao4: 0 }, prompt: 'Using the index data, explain what has happened to OF’s membership growth relative to the overall market since 2024.', markingGuidance: ['OF index rises from 100 to 121 while market rises from 100 to 111.','OF membership has grown faster than the market over the period, so its share of total memberships would have increased if the indices refer to the same market definition.','Interpret the indices rather than treating 121 as 121 members or 121%.'] },
    { id: 'of-q2', marks: 4, topic: 'finance', assessmentObjectives: { ao1: 2, ao2: 2, ao3: 0, ao4: 0 }, prompt: 'Calculate OF’s monthly contribution per member.', markingGuidance: ['Contribution = selling price − variable cost.','£34 − £6 = £28 per member per month.'] },
    { id: 'of-q3', marks: 8, topic: 'marketing', assessmentObjectives: { ao1: 2, ao2: 3, ao3: 3, ao4: 0 }, prompt: 'Analyse one possible benefit of expanding OF’s premium offer.', markingGuidance: ['Use segmentation and the stated premium customer preferences.','Develop into differentiation, willingness to pay, retention or contribution.','Recognise that the benefit depends on delivery quality and segment size.'] },
    { id: 'of-q4', marks: 10, topic: 'operations', assessmentObjectives: { ao1: 3, ao2: 2, ao3: 5, ao4: 0 }, prompt: 'Analyse the possible impact of closing eight gyms and investing in larger regional sites.', markingGuidance: ['Possible benefits: improved utilisation, automation and lower unit costs.','Possible drawbacks: reduced convenience, member losses, implementation cost and local competition.','Connect operations decisions to marketing and financial outcomes.'] },
    { id: 'of-q5', marks: 14, topic: 'hr', assessmentObjectives: { ao1: 3, ao2: 3, ao3: 3, ao4: 5 }, prompt: 'Assess whether OF should decentralise more decision making to local gym managers.', markingGuidance: ['Use local customer knowledge and current engagement concerns.','Counter with brand consistency, safety, cost control and the need for common standards.','Reach a conditional judgement about which decisions should be local versus central.'] },
    { id: 'of-q6', marks: 20, topic: 'marketing', assessmentObjectives: { ao1: 4, ao2: 4, ao3: 5, ao4: 7 }, prompt: 'Should OF continue increasing membership prices to improve profit? Justify your answer.', markingGuidance: ['Use contribution, fixed-cost pressure, cancellations, segmentation and price sensitivity.','Analyse the possibility of differentiated pricing rather than assuming one price for all.','Consider competitor entry and the premium offer.','Conclude based on elasticity by segment and whether higher prices damage retention enough to outweigh margin gains.'] },
    { id: 'of-q7', marks: 20, topic: 'leadership', assessmentObjectives: { ao1: 5, ao2: 3, ao3: 4, ao4: 8 }, prompt: '“For OF, responding to local customer needs matters more than improving operational efficiency through larger sites.” To what extent do you agree?', markingGuidance: ['Local case: decentralisation, convenience, customer segmentation and competition.','Efficiency case: capacity use, automation, unit costs, central brand and purchasing decisions.','Draw together operations, marketing, HR and finance.','Reach a clear conditional judgement linked to OF’s current strategic problem.'] },
  ],
})

export const extendedExams = [lumenHotelsExam, orbitFitnessExam]
