import { formulaSchema, topicLinkSchema, type Formula, type TopicLink } from '../../../schema'

const rawFormulas: Formula[] = [
  ['profit','Profit','Revenue − total costs'],['revenue','Revenue','Selling price × quantity sold'],['total-cost','Total cost','Fixed costs + total variable costs'],['market-share','Market share','Business sales ÷ total market sales × 100'],['market-growth','Market growth','Change in market size ÷ original market size × 100'],['percentage-change','Percentage change','Change ÷ original value × 100'],['market-capitalisation','Market capitalisation','Share price × number of issued shares'],['labour-productivity','Labour productivity','Output ÷ labour input'],['unit-cost','Unit cost','Total cost ÷ units produced'],['capacity-utilisation','Capacity utilisation','Actual output ÷ maximum output × 100'],['contribution-unit','Contribution/unit','Selling price − variable cost/unit'],['total-contribution','Total contribution','Contribution/unit × units sold'],['break-even-output','Break-even output','Fixed costs ÷ contribution/unit'],['margin-of-safety','Margin of safety','Actual or forecast output − break-even output'],['gross-profit-margin','Gross profit margin','Gross profit ÷ revenue × 100'],['operating-profit-margin','Operating profit margin','Operating profit ÷ revenue × 100'],['profit-for-year-margin','Profit for year margin','Profit for year ÷ revenue × 100'],['labour-turnover','Labour turnover','Leavers ÷ average number employed × 100'],['employee-cost-turnover','Employee cost % turnover','Employee costs ÷ turnover × 100'],['labour-cost-unit','Labour cost/unit','Total labour cost ÷ units produced'],['expected-value','Expected value','Σ (probability × outcome)'],['net-gain','Net gain','Expected value − cost of decision'],['cash-closing-balance','Cash-flow closing balance','Opening balance + net cash flow'],
].map(([id,name,expression]) => ({ id, name, expression }))

export const formulas = rawFormulas.map((formula) => formulaSchema.parse(formula))

const rawLinks: TopicLink[] = [
  ['business-objectives','business','Objectives','Objective changes alter finance, marketing, HR and operations priorities. Exam chain: growth objective → more investment/capacity → higher short-term cash need → source-of-finance decision.'],
  ['business-ownership','business','Ownership','Ownership affects access to finance, liability, control and objectives. Exam chain: LTD → limited private equity options → loan/retained profit more important → growth speed may be constrained.'],
  ['business-external','business','External environment','External changes hit demand/costs and force functional responses. Exam chain: interest rates rise → borrowing/customer spending pressure → demand or finance costs change → investment decision may be delayed.'],
  ['business-index-numbers','business','Index numbers','Index numbers show relative change from a base period usually set to 100. An index of 118 means the measure is 18% above the base; 94 means 6% below it. Compare index movements carefully: if the market index rises from 100 to 120 while a business sales index rises only to 110, the business has grown but more slowly than its market, so its market share is likely to have fallen.'],
  ['leadership-style','leadership','Leadership style','Style affects speed, information quality and employee commitment. Democratic decision → more staff input → better local information/acceptance → implementation may improve, but decision takes longer.'],
  ['leadership-trees','leadership','Decision trees','Quantifies uncertain choices, but assumptions matter. Higher expected value → looks attractive → yet if probabilities are weak or cash exposure is large → manager may rationally reject it.'],
  ['leadership-stakeholders','leadership','Stakeholders','A decision can create winners and losers. Wage rise → employees benefit → cost rises → shareholder return may fall unless productivity/retention improves.'],
  ['marketing-research','marketing','Research','Better evidence can reduce decision risk. Research identifies a segment → targeted mix improves relevance → conversion/loyalty may rise → marketing spend becomes more productive.'],
  ['marketing-segmentation','marketing','Segmentation','Target choice changes product, price, promotion and distribution. Niche target → tailored offer → differentiation/price premium → lower scale but stronger loyalty.'],
  ['marketing-7ps','marketing','7Ps','The mix links directly to finance and operations. Lower price → demand rises → capacity utilisation rises → unit costs may fall, but quality/capacity pressure may rise.'],
  ['operations-capacity','operations','Capacity','Capacity connects sales forecasts to cost and customer service. Demand growth → utilisation rises → unit cost may fall → but delays/quality failures can harm brand.'],
  ['operations-jit','operations','Lean/JIT','Inventory decision connects cash flow to supply risk. JIT → less inventory cash tied up → improved cash flow → but supplier delay can stop output and sales.'],
  ['operations-quality','operations','Quality','Quality links operations to marketing and finance. Assurance investment → fewer defects → lower returns + better reputation → repeat sales/margins may improve.'],
  ['finance-cash','finance','Cash flow','Cash connects every decision. Rapid growth → more inventory/staff before receipts → cash outflows precede inflows → profitable growth can still create insolvency risk.'],
  ['finance-break-even','finance','Break-even','Break-even links price, cost and demand. Automation raises fixed cost but lowers variable cost → break-even may initially rise/fall depending on contribution → high-volume firms may benefit more.'],
  ['finance-choice','finance','Finance choice','Funding affects risk/control. Equity → no scheduled loan repayment → cash pressure lower → but ownership/control diluted.'],
  ['hr-motivation','hr','Motivation','HR choices change operations and customer outcomes. Enrichment → higher engagement → productivity/quality may rise → unit cost or retention can improve.'],
  ['hr-structure','hr','Structure','Structure changes decision speed/control. Decentralisation → local managers decide faster → better customer response → but inconsistent decisions may weaken brand/control.'],
  ['hr-turnover','hr','Turnover','Turnover links HR, cost and quality. High turnover → recruitment/training + inexperienced staff → cost rises/quality falls → profit and reputation can decline.'],
].map(([id,topic,label,explanation]) => ({ id, topic, label, explanation })) as TopicLink[]

export const topicLinks = rawLinks.map((link) => topicLinkSchema.parse(link))
