import { topicSchema, type Topic } from '../../../schema'

const rawTopics: Topic[] = [
  {
    id: 'business', order: 1, title: '1. What is Business?', shortTitle: 'Business', sections: [
      { id: 'purpose-objectives-profit', title: 'Purpose, objectives & profit', points: ['Businesses exist to satisfy needs/wants while pursuing objectives such as survival, profit, growth, cash flow or social aims.','Mission is the broad purpose; objectives convert it into measurable priorities.','Profit = revenue − total costs. Revenue = price × quantity sold. Total cost = fixed + variable costs.','Objectives can conflict: growth may require short-term spending; lower prices may grow share but reduce margin.'] },
      { id: 'business-forms-ownership', title: 'Business forms & ownership', points: ['Sole traders retain control but carry unlimited liability.','Private limited companies offer limited liability but shares are privately held.','Public limited companies can raise substantial equity finance but face greater disclosure and shareholder pressure.','Non-profits and social enterprises may prioritise mission alongside financial sustainability.','Ownership affects objectives, finance options, control and stakeholder expectations.','Market capitalisation = share price × number of issued shares; a changing share price can affect investor confidence and takeover vulnerability.','A dividend is a payment to shareholders from distributable profits; retaining profit instead can finance growth.'] },
      { id: 'external-environment', title: 'External environment', points: ['Competition, market conditions, incomes and interest rates can change demand and costs.','Demographic change can alter customer segments and labour supply.','Environmental and ethical pressures can affect sourcing, operations, reputation and willingness to pay.','Paper 2 technique: never mention an external factor without explaining how it changes a business decision.'] },
      { id: 'influences-business-decisions', title: 'Influences on business decisions', points: ['Decisions are influenced by mission, objectives, ethics, resource constraints, stakeholder pressure, competition and the external environment.','A strong Paper 2 answer explains why the same factor can matter differently depending on the business context and objective.','Public-sector organisations are owned/controlled by government and may prioritise service, access or value for money rather than profit.','Shareholders may seek dividends and capital growth; their objectives can conflict with employees, customers or long-term reinvestment.','Fair trade and ethical choices can raise input costs but may improve reputation, differentiation and stakeholder trust.'] },
    ],
  },
  {
    id: 'leadership', order: 2, title: '2. Managers, Leadership & Decisions', shortTitle: 'Leadership', sections: [
      { id: 'leadership-styles', title: 'Leadership styles', points: ['Management organises resources; leadership influences direction and people.','Autocratic: leader decides; fast and clear, but may reduce involvement.','Paternalistic: leader decides while considering employee welfare.','Democratic: employees contribute; can improve ideas/commitment but slow decisions.','Laissez-faire: high freedom; can suit skilled teams but risks weak coordination.','Tannenbaum–Schmidt shows leadership as a continuum from manager-centred to subordinate-centred.'] },
      { id: 'decision-making', title: 'Decision making', points: ['Scientific decisions use data/models; intuition uses experience and judgement.','Decision trees compare expected monetary values but probability estimates may be unreliable.','Expected value = probability × outcome, summed across possible outcomes.','Net gain = expected value − cost of decision.','Risk has knowable probabilities; uncertainty is harder to quantify.','Opportunity cost is the next best alternative sacrificed.'] },
      { id: 'stakeholders', title: 'Stakeholders', points: ['Stakeholders include owners, employees, customers, suppliers, government and communities.','Power–interest mapping helps decide how closely different stakeholders should be managed.','Needs can overlap or conflict, e.g. higher wages versus shareholder returns.','Communication and consultation can reduce resistance and improve information quality.'] },
    ],
  },
  {
    id: 'marketing', order: 3, title: '3. Marketing Management', shortTitle: 'Marketing', sections: [
      { id: 'objectives-markets-research', title: 'Objectives, markets & research', points: ['Marketing objectives can target sales volume/value, growth, market share, market size and brand loyalty.','Primary research is collected first-hand; secondary research already exists.','Qualitative data explores reasons/opinions; quantitative data is numerical.','Sampling may be random, stratified or quota. Sample quality matters as much as sample size.','Correlation does not prove causation; extrapolation projects trends beyond observed data.','A confidence interval gives a range around an estimate; wider uncertainty should make managers more cautious.'] },
      { id: 'elasticity-segmentation', title: 'Elasticity & segmentation', points: ['Price elasticity shows responsiveness of demand to price changes; AQA AS requires interpretation rather than calculation.','Income elasticity shows responsiveness of demand to income changes.','Segmentation divides the market by factors such as demographics, geography, income or behaviour.','Targeting chooses which segment(s) to serve; positioning shapes how customers perceive the offer.','Niche markets can command loyalty/premium prices but have limited scale; mass markets offer scale but intense competition.'] },
      { id: 'marketing-mix', title: 'Marketing mix', points: ['7Ps: Product, Price, Promotion, Place, People, Process, Physical evidence.','Product portfolio tools include the Boston Matrix; product life cycle stages help guide promotion, investment and extension strategies.','Penetration pricing sets a relatively low launch price to build adoption; skimming uses a high initial price where willingness to pay is strong.','Promotion can include branding, social media and viral approaches.','Place includes multi-channel distribution; digital marketing/e-commerce can expand reach and data capture.','The mix must be integrated: one P can undermine another if positioning becomes inconsistent.','Boston Matrix: Stars, Cash Cows, Question Marks and Dogs help discuss portfolio balance, but labels depend on market-growth/share assumptions.','Product life cycle: introduction, growth, maturity and decline; extension strategies aim to prolong sales.','Digital marketing and e-commerce can widen reach, improve targeting/data and lower some distribution costs, but intensify price transparency and competition.'] },
      { id: 'technology-relationships-pricing', title: 'Technology, relationships & pricing', points: ['Relationship marketing aims to retain customers and increase lifetime value through ongoing engagement, service and personalised communication.','Dynamic pricing changes prices in response to factors such as demand, capacity, time or customer behaviour; it may improve revenue but can create fairness/reputation concerns.','Market mapping plots competing offers against two characteristics to identify positioning and possible gaps.','New product development can create growth and differentiation but carries research, development, launch and failure risk.','Income elasticity shows how demand responds to income changes; managers should interpret positive/negative values and relative responsiveness.'] },
      { id: 'integrated-marketing-mix', title: 'Integrated marketing mix', points: ['The integrated mix must fit product type, target market, positioning, competition, marketing objectives, product life-cycle stage and portfolio position.','Changing one P can force changes elsewhere: a premium price needs a product, promotion, people/process and physical evidence that support the premium position.'] },
    ],
  },
  {
    id: 'operations', order: 4, title: '4. Operational Management', shortTitle: 'Operations', sections: [
      { id: 'objectives-performance', title: 'Objectives & performance', points: ['Operational objectives include cost, quality, speed, flexibility, environmental performance and added value.','Labour productivity = output ÷ number of employees (or labour input where specified).','Unit cost = total cost ÷ units produced.','Capacity is maximum possible output in a period.','Capacity utilisation = actual output ÷ maximum output × 100.','Very high utilisation can lower unit costs but leave little spare capacity for surges, maintenance or disruption.'] },
      { id: 'efficiency-lean-technology', title: 'Efficiency, lean & technology', points: ['Efficiency means achieving output with minimum wasted resources; productivity measures output per input.','Lean production removes waste; Just in Time minimises inventory, while Just in Case holds protection against disruption.','Capital-intensive production can improve consistency and output but requires investment and may reduce flexibility.','Labour-intensive production can offer flexibility/personal service but exposes the business to wage and skills pressures.','Technology can automate tasks, improve inventory visibility and link customers/suppliers.'] },
      { id: 'quality-inventory-supply-chain', title: 'Quality, inventory & supply chain', points: ['Quality control inspects output; quality assurance builds quality into processes.','Poor quality can cause rework, returns, lost reputation and lower repeat purchase.','Inventory choices depend on demand uncertainty, lead times, storage cost and supply risk.','Key inventory-chart ideas: buffer stock, reorder level, reorder quantity and lead time.','Businesses can match capacity to demand via outsourcing, temporary/part-time workers or producing to order.','Supplier choice should consider reliability, quality, price, flexibility, ethics and strategic risk.','Outsourcing can add specialist capability/flexibility but reduces direct control and creates supplier dependency.','Temporary/part-time labour and producing to order can help match capacity to demand, but may affect skills, consistency or speed.'] },
      { id: 'inventory-charts-improving-performance', title: 'Inventory charts & improving performance', points: ['Inventory-control charts can show buffer stock, reorder level, reorder quantity, maximum inventory and lead time.','Longer lead times or less reliable suppliers may justify a higher reorder level or buffer stock.','Productivity can improve through training, technology, better job design, lean methods and process redesign.','Efficiency improvements can reduce cost but may damage flexibility, quality, resilience or employee engagement if pushed too far.','When interpreting an operations graph, identify the trend/number first, then explain the business consequence.'] },
    ],
  },
  {
    id: 'finance', order: 5, title: '5. Financial Management', shortTitle: 'Finance', sections: [
      { id: 'objectives-profit', title: 'Objectives & profit', points: ['Financial objectives include revenue, cost, profit, cash flow and return on investment targets. Return on investment asks whether the benefit earned justifies the capital committed.','Cash is money available to pay obligations; profit is revenue minus costs. A profitable firm can still run out of cash.','Gross profit = revenue − cost of sales.','Operating profit = gross profit − operating expenses.','Profit for the year accounts for the remaining finance/tax items relevant to the statement.'] },
      { id: 'budgets-cash-flow-break-even', title: 'Budgets, cash flow & break-even', points: ['Budgets set planned income/costs; variance compares actual with budget. Whether a variance is favourable depends on what is being measured.','Cash-flow forecasts show timing of inflows and outflows and can expose shortages before they occur.','Contribution per unit = selling price − variable cost per unit.','Break-even output = fixed costs ÷ contribution per unit.','Margin of safety = actual/forecast output − break-even output.','Total contribution = contribution per unit × units sold (or total revenue − total variable costs).','Break-even is useful for scenarios but assumes simplified cost/revenue relationships.'] },
      { id: 'profitability-finance', title: 'Profitability & finance', points: ['Profit margins help compare profit relative to revenue; a rising absolute profit does not automatically mean better profitability.','Gross, operating and profit-for-the-year margins compare each profit measure with revenue × 100.','Receivables delay cash coming in; payables delay cash going out.','Internal finance includes retained profit; external sources include overdrafts, loans, share capital, venture capital, crowdfunding and factoring.','Short-term needs should not automatically be funded with long-term finance, and vice versa.','Choice depends on cost, risk, control, duration, cash-flow reliability and business form.'] },
      { id: 'improving-cash-flow-profit', title: 'Improving cash flow & profit', points: ['Improve cash flow by accelerating inflows, delaying/controlling outflows, managing inventory or arranging appropriate finance.','Improve profit by increasing revenue, contribution, productivity or reducing avoidable costs.','A measure that improves cash today may damage long-term profit, supplier relations, quality or growth.'] },
      { id: 'constructing-forecasts-charts', title: 'Constructing forecasts & charts', points: ['A cash-flow forecast records expected cash inflows, cash outflows, net cash flow and opening/closing balances by period.','Closing balance = opening balance + net cash flow; a negative forecast balance signals a financing or timing problem.','Budgets set planned figures and variance analysis compares actual with budget; cost and revenue variances must be interpreted in context.','A break-even chart plots total revenue and total costs; their intersection is break-even output.','Higher fixed costs normally raise break-even; a higher selling price or lower variable cost raises contribution and normally lowers break-even, other things equal.'] },
    ],
  },
  {
    id: 'hr', order: 6, title: '6. Human Resource Management', shortTitle: 'HR', sections: [
      { id: 'objectives-performance', title: 'Objectives & performance', points: ['HR objectives include engagement, talent development, training, diversity, values alignment and having the right number/skills/location of employees.','Hard HRM treats labour more as a cost/resource; soft HRM emphasises development, commitment and involvement.','Labour turnover measures employees leaving relative to the workforce.','Employee costs as % of turnover and labour cost per unit help assess workforce cost efficiency.','Low labour cost is not automatically good if quality, retention or customer service suffers.'] },
      { id: 'structure-workforce-flow', title: 'Structure & workforce flow', points: ['Structures may be functional, product-based, regional or matrix.','Span of control, hierarchy, delegation, authority, centralisation and decentralisation shape speed, control and accountability.','Decentralisation can improve local responsiveness; centralisation can improve consistency and control.','HR planning anticipates workforce needs; flow includes recruitment, training, redeployment and redundancy.'] },
      { id: 'motivation-engagement', title: 'Motivation & engagement', points: ['Taylor emphasises financial reward linked to output; Maslow presents a hierarchy of needs; Herzberg separates hygiene factors from motivators.','Maslow moves from basic/secure needs through social and esteem towards self-actualisation; the model is useful for thinking about different needs but people do not always follow a fixed sequence.','Financial methods include piece rate, commission, salary and performance-related pay.','Non-financial methods include empowerment, team working, flexible working, job enrichment and rotation.','Motivation methods must fit the task, employee needs, measurability and business culture.'] },
      { id: 'employee-relations', title: 'Employee relations', points: ['Employee voice may involve trade unions, works councils and other consultation routes. Trade unions represent employee interests; works councils provide a formal employee-management consultation forum.','Good relations can improve trust, change adoption, retention and information flow.','Poor relations can increase conflict, disruption, turnover and reputational risk.','Evaluation: employee involvement can slow a decision but improve the probability of successful implementation.'] },
      { id: 'technology-labour-markets-hr-flow', title: 'Technology, labour markets & HR flow', points: ['Technology can change required skills, job design, communication, monitoring and where work is performed, including remote working.','Labour-market conditions affect recruitment difficulty, wage pressure, retention and the bargaining power of employees.','Human-resource flow should be seen as a connected process: workforce plan → recruitment → training/development → redeployment or redundancy when needs change.','Remote working may widen recruitment and improve flexibility but can make coordination, culture, supervision or training harder.'] },
    ],
  },
]

export const topics = rawTopics.map((topic) => topicSchema.parse(topic))
