import { examSchema } from '../../../schema'

export const paper2Exam = examSchema.parse({
  id: 'aqa-a-level-7132-paper-2-sim-1',
  title: 'AQA A-level Business — Paper 2 Simulation 1',
  subtitle: 'Original Revision-authored AQA-aligned data-response simulation',
  durationMinutes: 120,
  totalMarks: 100,
  caseHtml: `<p><strong>Original Revision simulation.</strong> AQA Paper 2 contains three compulsory data-response questions. The current Revision exam engine stores one stimulus field, so the three independent contexts are presented below as clearly separated data-response blocks. This is not an official AQA paper or an exact reproduction of the paper layout.</p>
  <hr><h3>Data Response 1 — Solace Skincare Ltd</h3>
  <p>Solace Skincare Ltd (SS) is a privately owned UK manufacturer of premium skincare products. It differentiates through refillable packaging and certified sustainable ingredients. Revenue in 2026 was £6.0m and operating profit was £480,000. Demand has grown rapidly after a large retailer began stocking the brand. The factory is forecast to operate at 93% capacity utilisation next year and customer complaints about late deliveries have increased.</p>
  <p>Management is considering switching more ingredients to a supplier charging 12% more than the current supplier. Marketing research suggests its target customers value environmental credentials, but several competitors have launched lower-priced ranges. SS is also considering a modest price increase.</p>
  <hr><h3>Data Response 2 — MetroRide plc</h3>
  <p>MetroRide plc (MR) operates shared electric-bike schemes in 14 UK cities. Local managers currently have limited authority because pricing, marketing and maintenance standards are set centrally. Customer demand differs substantially by city. Employee engagement among local operations teams has fallen.</p>
  <p>MR is considering acquiring a smaller competitor. Before the acquisition MR has capital employed of £30m and non-current liabilities of £9m. The target would add technology, local contracts and 80,000 members but would require additional borrowing. The board expects purchasing and technology synergies but is concerned about integration and higher gearing.</p>
  <hr><h3>Data Response 3 — Aster Cloud Ltd</h3>
  <p>Aster Cloud Ltd (AC) sells data-security software to medium-sized businesses. UK growth is slowing and management is considering entering Canada through an alliance with a local technology provider. AC also wants to invest in a new AI-supported threat-detection platform. One forecast gives a 55% chance of generating £2.4m contribution and a 45% chance of £0.8m contribution. The development programme would cost £1.1m.</p>
  <p>AC has large amounts of customer-usage data and believes data mining could improve its product and marketing. However, the project would require scarce specialist developers and could delay improvements requested by existing customers. Larger global competitors are also investing heavily.</p>`,
  questions: [
    { id:'p2-q01', marks:4, topic:'finance', assessmentObjectives:{ao1:1,ao2:3,ao3:0,ao4:0}, prompt:'Data Response 1 — Calculate SS’s 2026 operating profit margin.', markingGuidance:['Operating profit margin = operating profit ÷ revenue × 100.','£480,000 ÷ £6,000,000 × 100 = 8%.','Show workings and %.'] },
    { id:'p2-q02', marks:6, topic:'marketing', assessmentObjectives:{ao1:2,ao2:3,ao3:1,ao4:0}, prompt:'Data Response 1 — Explain one reason why SS may choose the higher-cost certified sustainable supplier.', markingGuidance:['Use the premium/sustainability target-market evidence.','Explain how stronger environmental credentials could support differentiation, brand trust, demand or willingness to pay.','Recognise the cost is 12% higher; the reason only creates value if customers care enough and the supplier performs reliably.'] },
    { id:'p2-q03', marks:9, topic:'operations', assessmentObjectives:{ao1:2,ao2:3,ao3:4,ao4:0}, prompt:'Data Response 1 — Analyse the possible impact on SS of forecast capacity utilisation of 93%.', markingGuidance:['High utilisation can spread fixed costs and make strong use of factory resources.','Use late-delivery complaints to analyse little spare capacity, disruption/maintenance risk and quality/service pressure.','Develop consequences for cost, customer satisfaction, retailer relationships and growth.'] },
    { id:'p2-q04', marks:14, topic:'marketing', assessmentObjectives:{ao1:3,ao2:3,ao3:4,ao4:4}, prompt:'Data Response 1 — Assess whether SS should increase its prices.', markingGuidance:['Analyse premium differentiation and customer interest in environmental credentials as possible support for pricing power.','Counter with lower-priced competitors and uncertainty about price sensitivity.','Connect price to contribution, volume, positioning and capacity pressure.','Reach a conditional judgement based on elasticity by target segment, competitor response and the size of the increase.'] },

    { id:'p2-q05', marks:4, topic:'strategic-position', assessmentObjectives:{ao1:1,ao2:3,ao3:0,ao4:0}, prompt:'Data Response 2 — Calculate MR’s gearing before the proposed acquisition using non-current liabilities ÷ capital employed × 100.', markingGuidance:['£9m ÷ £30m × 100 = 30%.','State the result as a percentage.'] },
    { id:'p2-q06', marks:6, topic:'hr', assessmentObjectives:{ao1:2,ao2:2,ao3:2,ao4:0}, prompt:'Data Response 2 — Explain how greater decentralisation could improve MR’s performance.', markingGuidance:['Apply different city demand conditions and low local-team engagement.','Local managers may use better local information and respond faster with marketing, capacity or maintenance decisions.','Develop the effect into customer use, cost, engagement or service while recognising that common standards still matter.'] },
    { id:'p2-q07', marks:9, topic:'strategic-methods', assessmentObjectives:{ao1:1,ao2:3,ao3:5,ao4:0}, prompt:'Data Response 2 — Analyse one possible synergy from acquiring the smaller competitor.', markingGuidance:['Use technology, contracts, members or purchasing evidence.','Explain why combining resources could create cost or revenue benefits greater than operating separately.','Do not assume synergy is automatic: integration quality, systems and culture affect whether it is realised.'] },
    { id:'p2-q08', marks:14, topic:'strategic-methods', assessmentObjectives:{ao1:3,ao2:2,ao3:3,ao4:6}, prompt:'Data Response 2 — Assess whether MR should acquire the smaller competitor.', markingGuidance:['Analyse faster external growth, members/contracts, technology and possible synergies.','Counter with borrowing/gearing, acquisition price, integration risk and loss of focus.','Compare external growth with organic alternatives where relevant.','Reach a supported judgement based on strategic fit, financing capacity and credible evidence that synergies exceed integration costs.'] },

    { id:'p2-q09', marks:4, topic:'leadership', assessmentObjectives:{ao1:1,ao2:3,ao3:0,ao4:0}, prompt:'Data Response 3 — Calculate the expected value and net gain of AC’s threat-detection platform using the forecast outcomes.', markingGuidance:['Expected value = (0.55 × £2.4m) + (0.45 × £0.8m) = £1.68m.','Net gain = £1.68m − £1.1m = £0.58m (£580,000).'] },
    { id:'p2-q10', marks:6, topic:'strategic-methods', assessmentObjectives:{ao1:2,ao2:2,ao3:2,ao4:0}, prompt:'Data Response 3 — Explain one benefit to AC of using an alliance to enter Canada.', markingGuidance:['A local partner may provide market knowledge, relationships, distribution or credibility with less capital commitment than direct investment.','Develop the chain into faster entry, reduced uncertainty or customer acquisition.','Recognise that partnership can reduce control or create dependence.'] },
    { id:'p2-q11', marks:10, topic:'strategic-methods', assessmentObjectives:{ao1:1,ao2:2,ao3:7,ao4:0}, prompt:'Data Response 3 — Analyse the possible strategic value of using data mining more extensively.', markingGuidance:['Use AC’s customer-usage data.','Analyse product improvement, threat detection, segmentation/personalisation or decision quality.','Develop limits through data quality, privacy/trust, scarce capability, cost and competitor imitation.','Keep the chain focused on competitive advantage rather than treating “more data” as automatically valuable.'] },
    { id:'p2-q12', marks:14, topic:'strategic-direction', assessmentObjectives:{ao1:2,ao2:1,ao3:1,ao4:10}, prompt:'Data Response 3 — Evaluate whether AC should prioritise entering Canada or developing the new threat-detection platform.', markingGuidance:['Compare market development with product development using Ansoff rather than treating either as risk-free.','Canada may diversify revenue geographically but requires local knowledge and partner dependence.','The product has a positive calculated net gain under the forecasts but uses scarce developers and may delay existing-customer needs.','Make the judgement using strategic fit, probability/forecast quality, customer retention, resource constraints and competitive urgency.','State what evidence would change the recommendation.'] },
  ],
})

export const exams = [paper2Exam]
