import { examSchema } from '../../../schema'

export const paper3Exam = examSchema.parse({
  id: 'aqa-a-level-7132-paper-3-sim-1',
  title: 'AQA A-level Business — Paper 3 Simulation 1',
  subtitle: 'Original Revision-authored integrated case-study simulation',
  durationMinutes: 120,
  totalMarks: 100,
  caseHtml: `<p><strong>Original Revision simulation.</strong> AQA Paper 3 uses one compulsory case study followed by approximately six questions. This simulation uses six questions and is designed to practise the integrated AO3/AO4 demand of the paper. It is not an official AQA paper or mark scheme.</p>
  <h3>Cedar Mobility plc</h3>
  <p>Cedar Mobility plc (CM) designs and manufactures electric delivery vans. It has two UK factories and sells to logistics businesses in the UK and several European countries. Revenue has grown strongly, but lower-cost competitors are entering the market. CM differentiates through vehicle reliability, software support and rapid maintenance.</p>
  <p>The main factory is forecast to operate at 94% capacity utilisation next year. Customer complaints about delivery delays have increased, although product reliability scores remain high. Labour turnover among software and engineering employees has risen to 18%. Employees say decision making is too centralised and that senior managers announce change before consulting technical teams.</p>
  <p><strong>Financial data for 2026:</strong> revenue £48m; operating profit £4.8m; capital employed £32m; current assets £9m; current liabilities £6m; non-current liabilities £12m. The board is willing to increase borrowing if a strategic project has sufficiently strong returns.</p>
  <p>CM is considering a £20m automated UK production facility. Forecast investment appraisal shows payback of 3 years 4 months, ARR of 18% and NPV of +£2.3m at the company’s chosen discount rate. The forecasts assume European demand continues to grow and that installation is completed on time.</p>
  <p>An alternative is direct investment in a smaller assembly facility in Poland. Labour and property costs are forecast to be lower and the site would be closer to some European customers. However, CM has little experience managing overseas production. Exchange rates, local recruitment, supply-chain coordination and maintaining the firm’s reliability standards are uncertain.</p>
  <p>The chief executive favours rapid expansion. The operations director argues that CM should first improve its existing UK systems, decentralise more technical decisions and involve employees in implementation. The board must decide both where to invest and how to manage the strategic change.</p>`,
  questions: [
    { id:'p3-q01', marks:12, topic:'operations', assessmentObjectives:{ao1:3,ao2:3,ao3:6,ao4:0}, prompt:'Analyse how CM may benefit from operating at a forecast 94% capacity utilisation.', markingGuidance:['Use 94% and the manufacturing context.','Possible chain: high utilisation → fixed costs spread across greater output → lower unit cost → improved ability to compete against lower-cost entrants or fund support/differentiation.','Recognise that the same high utilisation creates risks; the question asks for benefit, but sophisticated analysis can qualify the chain using delivery-delay evidence.'] },
    { id:'p3-q02', marks:12, topic:'hr', assessmentObjectives:{ao1:3,ao2:3,ao3:6,ao4:0}, prompt:'Analyse how greater decentralisation could affect CM’s performance.', markingGuidance:['Use technical-team dissatisfaction and the need for specialist engineering/software knowledge.','Decentralisation may improve decision speed, information quality, engagement and implementation.','Develop possible drawbacks such as inconsistent decisions, weaker strategic control or coordination across factories/markets.','Keep effects linked to CM rather than presenting generic advantages and disadvantages.'] },
    { id:'p3-q03', marks:16, topic:'strategic-position', assessmentObjectives:{ao1:3,ao2:3,ao3:5,ao4:5}, prompt:'Evaluate what CM’s 2026 financial data suggests about its ability to finance further growth.', markingGuidance:['Useful calculations: operating profit margin = £4.8m ÷ £48m = 10%; ROCE = £4.8m ÷ £32m = 15%; current ratio = £9m ÷ £6m = 1.5:1; gearing = £12m ÷ £32m × 100 = 37.5%.','Interpret rather than label: profitability/returns and liquidity provide evidence, while extra borrowing would change risk and financing commitments.','Compare ratios with objectives, cash-flow reliability, interest rates and project returns; no single ratio determines affordability.','Reach a supported judgement about financial capacity and what additional information is needed.'] },
    { id:'p3-q04', marks:16, topic:'strategic-position', assessmentObjectives:{ao1:3,ao2:3,ao3:5,ao4:5}, prompt:'To what extent should the investment-appraisal results persuade CM to build the new automated UK facility?', markingGuidance:['Use all three results: 3 years 4 months payback, 18% ARR and +£2.3m NPV. Explain what each contributes.','Positive NPV and strong ARR may support investment; payback informs the duration of financial exposure.','Evaluate assumptions: European demand, completion timing, £20m financing, automation implementation, employee response and alternative Polish investment.','Conclude on how much weight the appraisal deserves, not simply whether the figures are positive.'] },
    { id:'p3-q05', marks:20, topic:'strategic-methods', assessmentObjectives:{ao1:4,ao2:3,ao3:5,ao4:8}, prompt:'Would you advise CM to invest directly in the Polish assembly facility rather than expand production in the UK? Justify your answer.', markingGuidance:['Poland case: lower forecast labour/property costs, customer proximity and international capacity versus local-management knowledge, exchange rates, recruitment, supply chain and reliability risk.','UK case: known environment, existing capability and automation appraisal versus current 94% utilisation, £20m cost and implementation/employee issues.','Use globalisation, direct investment, cost reduction/local responsiveness, capabilities and finance.','Make a conditional recommendation based on the strategic constraint CM most needs to solve and evidence needed before commitment.'] },
    { id:'p3-q06', marks:24, topic:'strategic-change', assessmentObjectives:{ao1:4,ao2:3,ao3:4,ao4:13}, prompt:'“For CM, how strategic change is implemented will be more important to long-term success than which growth option the board chooses.” To what extent do you agree? Justify your answer.', markingGuidance:['Build the implementation case using 18% skilled-employee turnover, centralisation complaints, consultation, culture, leadership, communication, structure and project execution.','Build the strategic-choice case using UK automation versus direct investment, capacity, competition, finance, international risk and long-term positioning.','Evaluate interdependence: a strong strategic option can fail through poor implementation, while excellent implementation cannot rescue a fundamentally unsuitable option.','Prioritise the most important constraint for CM now and explain how the conclusion could change as conditions change.','A strong final judgement compares magnitude, reversibility, probability, time horizon and evidence quality rather than simply saying “both are important”.'] },
  ],
})

export const exams = [paper3Exam]
