import { flashcardSchema } from '../../../schema'

type CardTuple = [string, string, string]

const cards: CardTuple[] = [
  ['business','What is the difference between a mission and an objective?','A mission states broad purpose/direction; objectives are more specific targets used to pursue and measure that mission.'],
  ['business','What is profit?','Revenue minus total costs.'],
  ['business','What is the difference between fixed and variable costs?','Fixed costs do not change directly with output in the relevant period; total variable costs change as output changes.'],
  ['business','What does limited liability mean?','Owners are generally liable only up to the amount invested rather than personally responsible for all company debts.'],
  ['business','Private limited company versus public limited company?','Both have limited liability; a private company has privately held shares, while a PLC can offer shares publicly and usually faces greater disclosure/shareholder pressure.'],
  ['business','Market capitalisation formula?','Share price × number of issued shares.'],
  ['business','Why do shareholders invest?','Potential dividends, capital growth and sometimes influence/control, depending on their stake and objectives.'],
  ['business','Why can a share-price fall matter to managers?','It may weaken investor confidence, increase takeover vulnerability and put pressure on management or financing decisions, though it does not automatically prove poor current performance.'],
  ['business','Give four external influences on costs or demand.','Examples: competition, market conditions, incomes, interest rates, demographic change and environmental/fair-trade pressures.'],
  ['business','Why can ethical sourcing affect both cost and demand?','It may increase input costs while improving reputation, differentiation or willingness to buy.'],

  ['leadership','Management versus leadership?','Management organises resources and delivery; leadership influences direction and people. The roles overlap in practice.'],
  ['leadership','Name the four AQA leadership styles.','Autocratic, paternalistic, democratic and laissez-faire.'],
  ['leadership','What does the Tannenbaum–Schmidt continuum show?','Leadership behaviour ranging from manager-centred control towards greater subordinate freedom.'],
  ['leadership','Scientific decision making versus intuition?','Scientific decisions emphasise data and structured analysis; intuition relies more on experience and judgement.'],
  ['leadership','Expected value formula?','Sum of probability × outcome for all possible outcomes.'],
  ['leadership','Net gain formula in a decision tree?','Expected value minus the cost of the decision.'],
  ['leadership','Risk versus uncertainty?','Risk involves probabilities that can be estimated; uncertainty is harder to quantify reliably.'],
  ['leadership','What is opportunity cost?','The value of the next best alternative sacrificed by a decision.'],
  ['leadership','What does a power–interest map help with?','Prioritising how closely different stakeholders should be managed, consulted, informed or monitored.'],
  ['leadership','Why can the highest expected value still be rejected?','Probabilities may be weak and qualitative factors, cash exposure, strategic fit, risk attitude and stakeholder effects can matter.'],

  ['marketing','Primary versus secondary research?','Primary research is collected for the current purpose; secondary research already exists.'],
  ['marketing','Qualitative versus quantitative data?','Qualitative data explores reasons/opinions; quantitative data is numerical.'],
  ['marketing','Name three AQA sampling methods.','Random, stratified and quota.'],
  ['marketing','What does correlation prove?','Only an association between variables, not that one caused the other.'],
  ['marketing','What is a confidence interval?','A range around an estimate that reflects uncertainty about the true value.'],
  ['marketing','Does AQA 7132 require calculation of PED or YED?','No. Students need to interpret elasticity data and analyse its implications, not calculate the elasticity coefficient.'],
  ['marketing','Market share formula?','Business sales ÷ total market sales × 100.'],
  ['marketing','What is STP?','Segmentation, targeting and positioning.'],
  ['marketing','List the 7Ps.','Product, Price, Promotion, Place, People, Process and Physical environment/evidence.'],
  ['marketing','What is market mapping?','Plotting competing products or brands against two characteristics to understand positioning and possible gaps.'],

  ['operations','Name common operational objectives.','Cost, quality, speed of response, flexibility, environmental objectives and added value.'],
  ['operations','Labour productivity formula?','Output ÷ labour input.'],
  ['operations','Unit cost formula?','Total cost ÷ units produced.'],
  ['operations','Capacity utilisation formula?','Actual output ÷ maximum output × 100.'],
  ['operations','Why can very high capacity utilisation be risky?','There is little spare capacity for demand surges, maintenance or disruption, which can increase delays and quality pressure.'],
  ['operations','JIT versus JIC?','JIT keeps minimal inventory and relies on timely supply; JIC holds more inventory as protection against uncertainty.'],
  ['operations','Quality assurance versus quality control?','Assurance builds prevention into processes; control focuses on checking or detecting defects.'],
  ['operations','What is reorder level?','The inventory level at which a new order is triggered.'],
  ['operations','What is lead time?','The time between placing an order and receiving the inventory.'],
  ['operations','Name three ways of matching supply to demand.','Outsourcing, temporary/part-time labour and producing to order.'],

  ['finance','Cash versus profit?','Cash flow concerns the timing of money entering/leaving; profit is revenue minus costs. A profitable business can still run out of cash.'],
  ['finance','Gross profit formula?','Revenue minus cost of sales.'],
  ['finance','Contribution per unit formula?','Selling price per unit minus variable cost per unit.'],
  ['finance','Break-even output formula?','Fixed costs ÷ contribution per unit.'],
  ['finance','Margin of safety formula?','Actual or forecast output minus break-even output.'],
  ['finance','What is variance analysis?','Comparing actual figures with budgeted figures and identifying favourable or adverse differences in context.'],
  ['finance','What is a receivable?','An amount owed to the business by a customer; it delays a cash inflow until collected.'],
  ['finance','Name four external finance sources in 7132.','Examples: debt factoring, overdraft, share capital, loans, venture capital and crowdfunding.'],
  ['finance','Why can cutting inventory improve cash but increase risk?','Less cash is tied up, but shortages can disrupt production or sales if demand or supply is uncertain.'],
  ['finance','Operating profit margin formula?','Operating profit ÷ revenue × 100.'],

  ['hr','Hard versus soft HRM?','Hard HRM emphasises labour as a resource/cost; soft HRM emphasises employee development, commitment and involvement.'],
  ['hr','Labour turnover formula?','Number leaving ÷ average number employed × 100.'],
  ['hr','Employee costs as percentage of turnover formula?','Employee costs ÷ turnover × 100.'],
  ['hr','Labour cost per unit formula?','Total labour cost ÷ units produced.'],
  ['hr','Name four organisational structures in 7132.','Functional, product-based, regional and matrix.'],
  ['hr','Centralisation versus decentralisation?','Centralisation keeps more decision authority near the top; decentralisation delegates more authority lower down or locally.'],
  ['hr','What is human-resource flow?','The connected process of HR planning, recruitment, training, redeployment and redundancy as needs change.'],
  ['hr','Name the three motivation theories specified by AQA.','Taylor, Maslow and Herzberg.'],
  ['hr','Name four non-financial motivation methods.','Examples: empowerment, team working, flexible working, job enrichment and job rotation.'],
  ['hr','Trade union versus works council?','A trade union represents employee interests and may bargain collectively; a works council is a formal employee-management consultation forum.'],

  ['strategic-position','Strategy versus tactics?','Strategy is the longer-term direction/approach used to achieve objectives; tactics are shorter-term actions used to implement it.'],
  ['strategic-position','In SWOT, which factors are internal?','Strengths and weaknesses are internal; opportunities and threats arise from the external environment.'],
  ['strategic-position','ROCE formula?','Operating profit ÷ capital employed × 100.'],
  ['strategic-position','Current ratio formula?','Current assets ÷ current liabilities, usually expressed as a ratio such as 1.5:1.'],
  ['strategic-position','Gearing formula used in this pack?','Non-current liabilities ÷ capital employed × 100.'],
  ['strategic-position','Receivables days formula?','Trade receivables ÷ revenue × 365.'],
  ['strategic-position','What is Elkington’s Triple Bottom Line?','A framework considering Profit, People and Planet when assessing performance.'],
  ['strategic-position','Name Porter’s five forces.','Threat of entry, buyer power, supplier power, rivalry and threat of substitutes.'],
  ['strategic-position','Which investment-appraisal methods are required?','Payback, average rate of return (ARR) and net present value (NPV).'],
  ['strategic-position','Why should ratios be compared rather than read alone?','Meaning depends on trends, competitors, objectives, business model and external conditions.'],

  ['strategic-direction','Name the four Ansoff directions.','Market penetration, market development, new product development and diversification.'],
  ['strategic-direction','What is market penetration?','Selling more existing products in existing markets.'],
  ['strategic-direction','What is market development?','Taking existing products into new markets.'],
  ['strategic-direction','What is new product development?','Creating new products for existing markets.'],
  ['strategic-direction','What is diversification?','Entering new markets with new products.'],
  ['strategic-direction','Name Porter’s three broad positioning approaches in the specification.','Low cost, differentiation and focus.'],
  ['strategic-direction','What is differentiation?','Competing through benefits or characteristics that customers value and see as meaningfully different.'],
  ['strategic-direction','What is a focus strategy?','Concentrating on a narrower market segment rather than serving the broad market.'],
  ['strategic-direction','What is competitive advantage?','An advantage in customer value or cost performance that supports stronger competitive outcomes.'],
  ['strategic-direction','Why can competitive advantage disappear?','Imitation, technology, new entrants, customer change or shifts in buyer/supplier power can erode it.'],

  ['strategic-methods','Organic versus external growth?','Organic growth develops the existing business; external growth combines with or uses other organisations.'],
  ['strategic-methods','Name three economies of scale specified by AQA.','Technical, purchasing and managerial economies of scale.'],
  ['strategic-methods','What are economies of scope?','Cost or capability benefits from producing or operating across a wider range using shared resources or competences.'],
  ['strategic-methods','What is overtrading?','Growing faster than the business can finance or resource, creating working-capital and operational pressure.'],
  ['strategic-methods','Horizontal versus vertical integration?','Horizontal combines businesses at the same production stage; vertical combines different stages, backward toward suppliers or forward toward customers/distribution.'],
  ['strategic-methods','Name four ways to become more innovative in 7132.','Kaizen, research and development, intrapreneurship and benchmarking.'],
  ['strategic-methods','How can innovation be protected?','AQA specifies patents and copyright as intellectual-property protections.'],
  ['strategic-methods','Name four international entry methods.','Export, licensing, alliances and direct investment.'],
  ['strategic-methods','Offshoring versus reshoring?','Offshoring moves activity abroad; reshoring brings activity back to the home country.'],
  ['strategic-methods','Which digital technologies are explicitly named in 7132 strategic methods?','Automation, e-commerce, big data and data mining.'],

  ['strategic-change','Name the four types/sources of change specified by AQA.','Internal, external, incremental and disruptive change.'],
  ['strategic-change','What is Lewin’s force-field analysis?','A framework comparing forces driving a change with forces restraining it.'],
  ['strategic-change','Name Kotter and Schlesinger’s four reasons for resistance.','Self-interest; fear/misunderstanding/lack of trust; different assessment of the situation; preference for the existing position/low tolerance of change.'],
  ['strategic-change','Name three of Kotter and Schlesinger’s six ways to overcome resistance.','Any three of: education/communication, participation/involvement, facilitation/support, negotiation/agreement, manipulation/co-option, explicit/implicit coercion.'],
  ['strategic-change','Name Handy’s four culture types.','Task, role, power and person culture.'],
  ['strategic-change','What is the critical path?','The sequence of project activities that determines the minimum completion time; delay to a critical activity delays the project unless time is recovered.'],
  ['strategic-change','What is total float?','How long a non-critical activity can be delayed without delaying overall project completion, based on the network assumptions.'],
  ['strategic-change','Planned versus emergent strategy?','Planned strategy is deliberately formulated in advance; emergent strategy develops as the organisation learns and responds.'],
  ['strategic-change','What is strategic drift?','When strategy changes too slowly and becomes increasingly misaligned with the external environment.'],
  ['strategic-change','Why is contingency planning valuable?','It prepares responses to plausible disruptions or alternative scenarios, reducing reaction time if conditions change.'],
]

export const flashcards = cards.map(([topic, prompt, answer], index) => flashcardSchema.parse({
  id: `a-level-flashcard-${String(index + 1).padStart(3, '0')}`,
  topic,
  prompt,
  answer,
}))
