import { formulaSchema, topicLinkSchema, type Formula, type TopicLink } from '../../../schema'

const rawFormulas: Formula[] = [
  ['profit','Profit','Revenue − total costs'],
  ['revenue','Revenue','Selling price × quantity sold'],
  ['total-cost','Total cost','Fixed costs + total variable costs'],
  ['market-share','Market share','Business sales ÷ total market sales × 100'],
  ['market-growth','Market growth','Change in market size ÷ original market size × 100'],
  ['percentage-change','Percentage change','Change ÷ original value × 100'],
  ['market-capitalisation','Market capitalisation','Share price × number of issued shares'],
  ['labour-productivity','Labour productivity','Output ÷ labour input'],
  ['unit-cost','Unit cost','Total cost ÷ units produced'],
  ['capacity-utilisation','Capacity utilisation','Actual output ÷ maximum output × 100'],
  ['contribution-unit','Contribution per unit','Selling price − variable cost per unit'],
  ['total-contribution','Total contribution','Contribution per unit × units sold'],
  ['break-even-output','Break-even output','Fixed costs ÷ contribution per unit'],
  ['margin-of-safety','Margin of safety','Actual or forecast output − break-even output'],
  ['gross-profit-margin','Gross profit margin','Gross profit ÷ revenue × 100'],
  ['operating-profit-margin','Operating profit margin','Operating profit ÷ revenue × 100'],
  ['profit-for-year-margin','Profit for year margin','Profit for year ÷ revenue × 100'],
  ['labour-turnover','Labour turnover','Number leaving ÷ average number employed × 100'],
  ['employee-cost-turnover','Employee costs as % of turnover','Employee costs ÷ turnover × 100'],
  ['labour-cost-unit','Labour cost per unit','Total labour cost ÷ units produced'],
  ['expected-value','Expected value','Σ (probability × outcome)'],
  ['net-gain','Net gain','Expected value − cost of decision'],
  ['cash-closing-balance','Cash-flow closing balance','Opening balance + net cash flow'],
  ['roce','Return on capital employed (ROCE)','Operating profit ÷ capital employed × 100'],
  ['current-ratio','Current ratio','Current assets ÷ current liabilities'],
  ['gearing','Gearing','Non-current liabilities ÷ capital employed × 100'],
  ['receivables-days','Receivables days','Trade receivables ÷ revenue × 365'],
  ['payables-days','Payables days','Trade payables ÷ cost of sales × 365'],
  ['inventory-turnover','Inventory turnover','Cost of sales ÷ average inventory'],
  ['arr','Average rate of return (ARR)','Average annual profit from project ÷ initial investment × 100'],
  ['npv','Net present value (NPV)','Total present value of future net cash flows − initial investment'],
].map(([id,name,expression]) => ({ id, name, expression }))

export const formulas = rawFormulas.map((formula) => formulaSchema.parse(formula))

const rawLinks: TopicLink[] = [
  ['objectives-chain','business','Objectives shape every function','Growth, profit, cash, social and ethical objectives create different priorities. A strategic answer should connect the stated objective to the marketing, operations, finance and HR choices it changes.'],
  ['ownership-finance','business','Ownership and finance','Business form affects control, liability and finance. A PLC can access public equity but shareholder expectations and share-price pressure can affect strategy.'],
  ['leadership-change','leadership','Leadership and strategic change','The right leadership approach depends on urgency, employee knowledge, resistance, culture and implementation risk. Democratic involvement may improve acceptance while autocratic direction may increase speed.'],
  ['decision-risk','leadership','Models and uncertainty','Decision trees and investment appraisal make assumptions visible, but expected values and forecasts are only as reliable as the underlying probabilities, cash flows and context.'],
  ['marketing-operations','marketing','Marketing creates operational consequences','A successful campaign or lower price can increase demand. If capacity and quality cannot respond, marketing success can create delays, defects and weaker customer experience.'],
  ['positioning-mix','marketing','Positioning must match the 7Ps','A premium position needs product, price, promotion, people, process, place and physical environment that consistently support the promised value.'],
  ['capacity-finance','operations','Capacity connects operations and finance','Higher utilisation may lower unit costs, but very high utilisation can increase delay/quality risk. Adding capacity needs finance and only creates value if demand is sufficient.'],
  ['inventory-cash','operations','Inventory connects resilience and cash','More buffer inventory can reduce stockout risk but ties up cash. JIT can improve working capital but increases dependence on reliable suppliers.'],
  ['quality-brand','operations','Quality connects operations and marketing','Quality assurance can reduce rework and support customer trust. Poor quality can turn an operational problem into refunds, reputation damage and weaker demand.'],
  ['cash-growth','finance','Growth can consume cash','Fast growth may require inventory, labour and capacity spending before receipts arrive. A profitable growth strategy can still create a liquidity problem or overtrading.'],
  ['ratios-context','strategic-position','Ratios tell a story only in context','ROCE, liquidity, gearing and efficiency ratios should be compared over time and against relevant businesses. The objective, economic environment and business model affect what a value means.'],
  ['hr-competitiveness','hr','People affect cost and customer value','Turnover, motivation, skills and organisational design affect productivity, quality, innovation and service, so HR decisions can create or destroy competitive advantage.'],
  ['swot-direction','strategic-position','Analysis should lead to a decision','SWOT is useful when it identifies the few internal and external issues that materially change strategic options. A list with no prioritisation is not strategic analysis.'],
  ['porter-direction','strategic-position','Five forces shape strategic options','Strong rivalry, powerful buyers/suppliers, substitutes or low entry barriers can reduce industry profitability and influence whether a business seeks cost advantage, differentiation or a different market.'],
  ['appraisal-strategy','strategic-position','Investment appraisal is one input','Payback, ARR and NPV answer different financial questions. Strategic fit, risk, capability, financing and stakeholder consequences still matter.'],
  ['ansoff-risk','strategic-direction','Direction changes the risk profile','Moving into new products or new markets increases unfamiliarity. Ansoff helps frame risk, but capability, data and execution determine the actual risk.'],
  ['scale-overtrading','strategic-methods','Growth can weaken a successful business','Economies and synergy can lower cost, but rapid growth can stretch cash, people and systems. Growth rate should match financing and management capability.'],
  ['global-supply','strategic-methods','International cost versus resilience','Offshoring or global sourcing may reduce cost, but exchange rates, political risk, lead times, quality and supply resilience can change the true strategic value.'],
  ['digital-people','strategic-methods','Technology changes more than cost','Automation and data can improve efficiency and decisions, but implementation depends on skills, culture, process redesign, trust and customer acceptance.'],
  ['change-implementation','strategic-change','Good strategy can fail in implementation','Leadership, communication, structure, culture, resources and project timing determine whether a strategic choice becomes actual performance.'],
  ['network-cash','strategic-change','Project timing has financial effects','Critical-path delays can postpone revenue, extend financing needs and increase costs. Float helps prioritise attention but depends on reliable duration estimates.'],
  ['drift-environment','strategic-change','Strategic drift is a moving gap','A strategy can become less appropriate when environmental change outpaces organisational response. Monitoring should trigger challenge, not automatic continuation of the existing plan.'],
].map(([id,topic,label,explanation]) => ({ id, topic, label, explanation })) as TopicLink[]

export const topicLinks = rawLinks.map((link) => topicLinkSchema.parse(link))
