import { dataDrillSchema } from '../../../schema'

const drills = [
  ['Market share','A market is worth £48m. A business has annual sales of £7.2m. Calculate market share and interpret it.','Market share = £7.2m ÷ £48m × 100 = 15%. The business accounts for 15% of total market sales by value. The percentage alone does not show whether share is rising or whether the market is attractive.'],
  ['Market growth','A market grows from £50m to £58m. Calculate market growth.','Growth = (£58m − £50m) ÷ £50m × 100 = 16%. This describes market growth, not the growth of any individual business.'],
  ['Index interpretation','A market index rises from 100 to 124 while a firm sales index rises from 100 to 116. Interpret the likely competitive implication.','Both have grown relative to the base period, but the market grew faster. If both indices refer to the same market definition, the firm is likely to have lost relative market share. Index values are relative measures, not percentages by themselves.'],
  ['Expected value and net gain','A project has a 55% chance of a £240,000 outcome and a 45% chance of an £80,000 outcome. It costs £110,000. Calculate expected value and net gain.','Expected value = (0.55 × £240,000) + (0.45 × £80,000) = £168,000. Net gain = £168,000 − £110,000 = £58,000. The calculation supports a decision but does not remove uncertainty.'],
  ['Capacity utilisation','A service centre can handle 2,400 appointments per month and handles 2,160. Calculate capacity utilisation and interpret one trade-off.','2,160 ÷ 2,400 × 100 = 90%. High utilisation may spread fixed costs well, but there is relatively little spare capacity for demand spikes, absence or disruption.'],
  ['Unit cost','A manufacturer incurs total production costs of £525,000 and makes 75,000 units. Calculate unit cost.','£525,000 ÷ 75,000 = £7 per unit. Managers should compare the figure over time or with alternatives and check whether quality/output mix has changed.'],
  ['Contribution and break-even','A product sells for £27, has variable cost of £12 per unit and fixed costs of £180,000. Calculate contribution per unit and break-even output.','Contribution per unit = £27 − £12 = £15. Break-even output = £180,000 ÷ £15 = 12,000 units.'],
  ['Margin of safety','A business forecasts sales of 15,500 units and break-even output of 12,000 units. Calculate margin of safety.','Margin of safety = 15,500 − 12,000 = 3,500 units. A larger margin gives more room for demand to fall before losses begin, assuming the model assumptions hold.'],
  ['Cash-flow closing balance','Opening cash is £18,000. Forecast inflows are £62,000 and outflows £75,000. Calculate closing cash.','Net cash flow = £62,000 − £75,000 = −£13,000. Closing balance = £18,000 − £13,000 = £5,000. The business remains positive but has less liquidity than at the start.'],
  ['Operating profit margin','Revenue is £12m and operating profit is £840,000. Calculate operating profit margin.','£840,000 ÷ £12,000,000 × 100 = 7%. This means operating profit is 7p per £1 of revenue before later finance/tax items.'],
  ['Labour turnover','During the year 42 employees leave. Average employment is 280. Calculate labour turnover.','42 ÷ 280 × 100 = 15%. Whether this is problematic depends on sector norms, skills lost, recruitment difficulty, costs and service/quality effects.'],
  ['Employee costs percentage','Employee costs are £2.1m and turnover is £8.4m. Calculate employee costs as a percentage of turnover.','£2.1m ÷ £8.4m × 100 = 25%. The figure needs comparison and context because labour intensity differs substantially between businesses.'],
  ['ROCE','Operating profit is £2.4m and capital employed is £16m. Calculate ROCE.','ROCE = £2.4m ÷ £16m × 100 = 15%. Interpretation should compare it with previous years, relevant competitors, financing conditions and the return expected by owners.'],
  ['Current ratio','Current assets are £5.4m and current liabilities £3.6m. Calculate the current ratio.','£5.4m ÷ £3.6m = 1.5:1. This suggests £1.50 of current assets for each £1 of current liabilities, but asset quality and the business model matter.'],
  ['Gearing','Non-current liabilities are £7.5m and capital employed is £25m. Calculate gearing using the Revision/AQA course formula.','£7.5m ÷ £25m × 100 = 30%. The risk implication depends on cash-flow reliability, interest rates, returns on borrowed funds and the wider capital structure.'],
  ['Receivables days','Trade receivables are £2.4m and annual revenue is £18m. Estimate receivables days.','£2.4m ÷ £18m × 365 = 48.7 days (approximately 49 days). A rise could indicate slower collection, but credit terms and customer mix should be checked.'],
  ['Payables days','Trade payables are £1.6m and annual cost of sales is £9.6m. Estimate payables days.','£1.6m ÷ £9.6m × 365 = 60.8 days (approximately 61 days). Longer payment can help cash flow but may reflect pressure or damage supplier relationships if terms are exceeded.'],
  ['Inventory turnover','Annual cost of sales is £9.6m and average inventory is £1.2m. Calculate inventory turnover.','£9.6m ÷ £1.2m = 8 times per year. Higher turnover may signal efficient inventory use, but too little stock can create shortages and lost sales.'],
  ['Payback','A project costs £400,000. Forecast net cash inflows are £140,000 in year 1, £160,000 in year 2, £180,000 in year 3 and £120,000 in year 4. Calculate payback.','After two years £300,000 has been recovered, leaving £100,000. In year 3 the project returns £180,000, so £100,000 ÷ £180,000 = 0.556 of a year ≈ 6.7 months. Payback is about 2 years 7 months.'],
  ['Average rate of return','The same four-year project costs £400,000 and generates total net cash inflows of £600,000. Treating the £200,000 surplus over the initial investment as total project profit, calculate ARR.','Total project profit = £600,000 − £400,000 = £200,000. Average annual profit = £200,000 ÷ 4 = £50,000. ARR = £50,000 ÷ £400,000 × 100 = 12.5%.'],
  ['Net present value','A project costs £600,000 today. After applying the chosen discount factors, the present values of forecast future net cash inflows are £91,000, £166,000, £225,000 and £272,000. Calculate NPV.','Total present value = £754,000. NPV = £754,000 − £600,000 = +£154,000. A positive NPV is financially favourable relative to the discount-rate benchmark, but forecasts and strategic factors still need evaluation.'],
  ['Investment comparison','Project A pays back in 2 years 2 months with ARR 11% and NPV £90,000. Project B pays back in 3 years with ARR 17% and NPV £155,000. Which is best?','There is no automatic answer without the business objective and risk context. A is stronger on speed/liquidity; B is stronger on average return and NPV. A justified choice should consider financing, risk, forecast reliability and strategic fit.'],
  ['Network path','A project has two complete paths: A–C–E takes 18 days and B–D–E takes 23 days. Which is the critical path if these are the only paths?','B–D–E is the critical path because it is the longest complete dependency path at 23 days and therefore determines the minimum project duration under the stated assumptions.'],
  ['Productivity comparison','Site A produces 18,000 units with 90 employees. Site B produces 21,000 units with 84 employees. Compare labour productivity.','Site A = 200 units per employee. Site B = 250 units per employee. Site B is 25% more productive on this measure, but managers should also consider quality, wage cost, capital input and product mix.'],
] as const

export const dataDrills = drills.map(([title, prompt, answer], index) => dataDrillSchema.parse({
  id: `a-level-data-drill-${String(index + 1).padStart(2, '0')}`,
  title,
  prompt,
  answer,
}))
