let testStarted=false,testList=[],testPos=0,testScore=0,answered=false;
function startDiagnostic(){showView("test");setTestMode("quick");startTest();}
function startTest(){testStarted=true;testScore=0;testPos=0;answered=false;testList=[...questions.keys()].sort(()=>Math.random()-.5).slice(0,10);renderQuestion();}
function renderQuestion(){const box=document.getElementById("quickTest");if(testPos>=testList.length){box.innerHTML=`<div class="eyebrow">Result</div><h2>${testScore} / ${testList.length}</h2><p>${testScore<5?"Repair knowledge gaps before pushing into long answers.":testScore<8?"Solid base. Now focus on application and analysis.":"Strong recall. Spend more time on case-study analysis and evaluation."}</p><button class="cta" onclick="startTest()">New mixed test</button>`;renderDashboard();return;}const qi=testList[testPos],q=questions[qi];answered=false;box.innerHTML=`<div class="flash-top"><span class="tag">${topics[q.t].short}</span><span class="small">Question ${testPos+1} / ${testList.length}</span></div><div class="test-q" style="margin-top:22px">${q.q}</div><div class="options">${q.o.map((o,i)=>`<button class="option" onclick="answerQ(${qi},${i},this)">${o}</button>`).join("")}</div><div id="qFeedback"></div>`;}
function answerQ(qi,choice,btn){if(answered)return;answered=true;const q=questions[qi],ok=choice===q.a;if(ok)testScore++;state.quiz[qi]=ok?1:0;save();[...btn.parentElement.children].forEach((el,i)=>{if(i===q.a)el.classList.add("correct");if(i===choice&&!ok)el.classList.add("wrong");el.disabled=true;});document.getElementById("qFeedback").innerHTML=`<div class="feedback"><strong>${ok?"Correct":"Not quite"}.</strong> ${q.e}</div><button class="cta" style="margin-top:12px" onclick="nextQ()">Next</button>`;}
function nextQ(){testPos++;renderQuestion();}
function setTestMode(m){document.getElementById("quickTest").style.display=m==="quick"?"block":"none";document.getElementById("caseTest").style.display=m==="case"?"block":"none";document.getElementById("quickTab").classList.toggle("active",m==="quick");document.getElementById("caseTab").classList.toggle("active",m==="case");if(m==="quick"&&!testStarted)startTest();if(m==="case")renderCase();}
function renderCase(){document.getElementById("caseTest").innerHTML=`<div class="case"><div class="card"><div class="eyebrow">Unseen-style case</div><h2>${caseStudy.title}</h2><div class="case-text">${caseStudy.text}</div></div><div class="card"><h3>Extract the evidence first</h3><p>Before answering, identify numbers, trends, constraints, objectives and stakeholder tension.</p><div class="case-facts">${caseStudy.facts.map(f=>`<div class="fact">${f}</div>`).join("")}</div><div class="callout" style="margin-top:14px"><strong>Rule:</strong> evidence is only application if you explain why it changes your argument.</div></div></div><div class="card" style="margin-top:15px"><h2>Case questions</h2><p>Answer aloud or on paper before opening the guidance.</p>${caseStudy.qs.map((q,i)=>`<details class="case-question"><summary>${i+1}. ${q[0]}</summary><div class="model">${q[1]}</div></details>`).join("")}</div>`;}
function resetProgress(){if(typeof resetRevisionProgress==="function")return resetRevisionProgress();if(window.confirm("Reset all saved revision progress on this device?")){localStorage.removeItem("paper2State");location.reload();}}
renderLearn();renderMind();renderFormulas();renderDashboard();buildFlashOrder();showView("home");
const v2Script=document.createElement('script');v2Script.src='v2.js';document.body.appendChild(v2Script);