const state = JSON.parse(localStorage.getItem("paper2State") || '{"cards":{},"quiz":{},"topic":{}}');
function save(){localStorage.setItem("paper2State",JSON.stringify(state));renderDashboard();}
const views=["home","learn","flashcards","mindmap","blueprint","test"];
const navLabels={home:"Dashboard",learn:"Learn",flashcards:"Recall",mindmap:"Connect",blueprint:"Answer",test:"Test"};
document.getElementById("nav").innerHTML=views.map(v=>`<button data-v="${v}" onclick="showView('${v}')">${navLabels[v]}</button>`).join("");
document.getElementById("mobileNav").innerHTML=views.map(v=>`<button onclick="showView('${v}')">${navLabels[v]}</button>`).join("");
function showView(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.getElementById(v).classList.add("active");document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.v===v));if(v==="flashcards")showFlash();if(v==="test"&&!testStarted)startTest();window.scrollTo({top:0,behavior:"smooth"});}
function topicMastery(k){const cards=flashcards.map((c,i)=>[c,i]).filter(x=>x[0][0]===k);if(!cards.length)return 0;let score=cards.reduce((s,x)=>s+(state.cards[x[1]]?.score||0),0);const quiz=Object.entries(state.quiz).filter(([i,r])=>questions[i]&&questions[i].t===k);let quizScore=quiz.length?quiz.filter(x=>x[1]===1).length/quiz.length*100:0;const cardPct=score/(cards.length*2)*100;return Math.round(cardPct*.7+quizScore*.3);}
function overall(){return Math.round(Object.keys(topics).reduce((s,k)=>s+topicMastery(k),0)/6);}
function renderDashboard(){const pct=overall();document.getElementById("readiness").textContent=pct+"%";document.getElementById("ring").style.setProperty("--pct",pct+"%");document.getElementById("statusLine").textContent=pct<25?"Build the foundations":pct<50?"Knowledge is forming":pct<70?"Move into application":pct<85?"Exam mode":"Strong readiness";const sorted=Object.keys(topics).sort((a,b)=>topicMastery(a)-topicMastery(b));const weak=sorted[0];document.getElementById("nextText").textContent=`Current weakest area: ${topics[weak].short}. Use recall, then apply it to a case question.`;document.getElementById("topicGrid").innerHTML=Object.keys(topics).map(k=>{const p=topicMastery(k);return `<div class="card topic-card" onclick="openTopic('${k}')"><div class="topic-head"><h3>${topics[k].name}</h3><b>${p}%</b></div><div class="bar"><i style="width:${p}%"></i></div><div class="small">${topics[k].subs.length} core blocks · click to revise</div></div>`;}).join("");document.getElementById("sessionPlan").innerHTML=`<div class="session-row"><span class="num">1</span><span style="flex:1"><b>Recall</b><br><span class="small">5 flashcards</span></span><b>5 min</b></div><div class="session-row"><span class="num">2</span><span style="flex:1"><b>${topics[weak].short}</b><br><span class="small">repair weakest area</span></span><b>7 min</b></div><div class="session-row"><span class="num">3</span><span style="flex:1"><b>Apply</b><br><span class="small">mixed exam questions</span></span><b>8 min</b></div>`;}
function openTopic(k){currentLearn=k;renderLearn();showView("learn");}
let currentLearn="all";
function renderFilters(id,fn,current){document.getElementById(id).innerHTML=`<button class="pill ${current==="all"?"active":""}" onclick="${fn}('all')">All</button>`+Object.keys(topics).map(k=>`<button class="pill ${current===k?"active":""}" onclick="${fn}('${k}')">${topics[k].short}</button>`).join("");}
function setLearn(k){currentLearn=k;renderLearn();}
function renderLearn(){renderFilters("learnFilters","setLearn",currentLearn);const keys=currentLearn==="all"?Object.keys(topics):[currentLearn];document.getElementById("learnList").innerHTML=keys.map(k=>`<div class="card"><h2 style="margin-top:0">${topics[k].name}</h2>${topics[k].subs.map(s=>`<details class="learn-section"><summary>${s[0]}</summary><ul>${s[1].map(x=>`<li>${x}</li>`).join("")}</ul></details>`).join("")}</div>`).join("");}
let flashFilter="all",flashOrder=[],flashPos=0;
function setFlash(k){flashFilter=k;flashPos=0;buildFlashOrder();showFlash();}
function buildFlashOrder(){flashOrder=flashcards.map((c,i)=>i).filter(i=>flashFilter==="all"||flashcards[i][0]===flashFilter);flashOrder.sort((a,b)=>(state.cards[a]?.score||0)-(state.cards[b]?.score||0));}
function showFlash(){renderFilters("flashFilters","setFlash",flashFilter);if(!flashOrder.length)buildFlashOrder();const idx=flashOrder[flashPos%flashOrder.length],c=flashcards[idx];document.getElementById("flashTag").textContent=topics[c[0]].short;document.getElementById("flashCount").textContent=`${flashPos%flashOrder.length+1} / ${flashOrder.length}`;document.getElementById("flashQ").textContent=c[1];document.getElementById("flashA").textContent=c[2];document.getElementById("flashA").classList.remove("show");document.getElementById("rateBtns").classList.remove("show");document.getElementById("revealBtn").style.display="inline-block";}
function revealCard(){document.getElementById("flashA").classList.add("show");document.getElementById("rateBtns").classList.add("show");document.getElementById("revealBtn").style.display="none";}
function rateCard(score){const idx=flashOrder[flashPos%flashOrder.length];state.cards[idx]={score,seen:(state.cards[idx]?.seen||0)+1};save();if(score===0){const[x]=flashOrder.splice(flashPos%flashOrder.length,1);flashOrder.splice(Math.min(flashPos+3,flashOrder.length),0,x);}else flashPos++;showFlash();}
function renderMind(){document.getElementById("mindGrid").innerHTML=Object.keys(topics).map(k=>`<div class="card mind-branch"><h3>${topics[k].short}</h3>${Object.keys(mindNodes[k]).map(n=>`<button onclick="mindDetail('${k}','${n.replace(/'/g,"\\'")}')"><b>${n}</b></button>`).join("")}</div>`).join("");}
function mindDetail(k,n){document.getElementById("mindDetail").innerHTML=`<div class="eyebrow">${topics[k].name}</div><h3>${n}</h3><p>${mindNodes[k][n]}</p><div class="callout"><strong>Paper 2 habit:</strong> add a case fact to the start of this chain, then question whether the final consequence is certain.</div>`;}
function renderFormulas(){document.getElementById("formulaGrid").innerHTML=formulas.map(f=>`<div class="card"><b>${f[0]}</b><div class="formula">${f[1]}</div></div>`).join("");}