const topics = {
business:{name:"1. What is Business?",short:"Business",subs:[
["Purpose, objectives & profit",["Businesses exist to satisfy needs/wants while pursuing objectives such as survival, profit, growth, cash flow or social aims.","Mission is the broad purpose; objectives convert it into measurable priorities.","Profit = revenue − total costs. Revenue = price × quantity sold. Total cost = fixed + variable costs.","Objectives can conflict: growth may require short-term spending; lower prices may grow share but reduce margin."]],
["Business forms & ownership",["Sole traders retain control but carry unlimited liability.","Private limited companies offer limited liability but shares are privately held.","Public limited companies can raise substantial equity finance but face greater disclosure and shareholder pressure.","Non-profits and social enterprises may prioritise mission alongside financial sustainability.","Ownership affects objectives, finance options, control and stakeholder expectations.","Market capitalisation = share price × number of issued shares; a changing share price can affect investor confidence and takeover vulnerability.","A dividend is a payment to shareholders from distributable profits; retaining profit instead can finance growth."]],
["External environment",["Competition, market conditions, incomes and interest rates can change demand and costs.","Demographic change can alter customer segments and labour supply.","Environmental and ethical pressures can affect sourcing, operations, reputation and willingness to pay.","Paper 2 technique: never mention an external factor without explaining how it changes a business decision."]]
]},
leadership:{name:"2. Managers, Leadership & Decisions",short:"Leadership",subs:[
["Leadership styles",["Management organises resources; leadership influences direction and people.","Autocratic: leader decides; fast and clear, but may reduce involvement.","Paternalistic: leader decides while considering employee welfare.","Democratic: employees contribute; can improve ideas/commitment but slow decisions.","Laissez-faire: high freedom; can suit skilled teams but risks weak coordination.","Tannenbaum–Schmidt shows leadership as a continuum from manager-centred to subordinate-centred."]],
["Decision making",["Scientific decisions use data/models; intuition uses experience and judgement.","Decision trees compare expected monetary values but probability estimates may be unreliable.","Expected value = probability × outcome, summed across possible outcomes.","Net gain = expected value − cost of decision.","Risk has knowable probabilities; uncertainty is harder to quantify.","Opportunity cost is the next best alternative sacrificed."]],
["Stakeholders",["Stakeholders include owners, employees, customers, suppliers, government and communities.","Power–interest mapping helps decide how closely different stakeholders should be managed.","Needs can overlap or conflict, e.g. higher wages versus shareholder returns.","Communication and consultation can reduce resistance and improve information quality."]]
]},
marketing:{name:"3. Marketing Management",short:"Marketing",subs:[
["Objectives, markets & research",["Marketing objectives can target sales volume/value, growth, market share, market size and brand loyalty.","Primary research is collected first-hand; secondary research already exists.","Qualitative data explores reasons/opinions; quantitative data is numerical.","Sampling may be random, stratified or quota. Sample quality matters as much as sample size.","Correlation does not prove causation; extrapolation projects trends beyond observed data.","A confidence interval gives a range around an estimate; wider uncertainty should make managers more cautious."]],
["Elasticity & segmentation",["Price elasticity shows responsiveness of demand to price changes; AQA AS requires interpretation rather than calculation.","Income elasticity shows responsiveness of demand to income changes.","Segmentation divides the market by factors such as demographics, geography, income or behaviour.","Targeting chooses which segment(s) to serve; positioning shapes how customers perceive the offer.","Niche markets can command loyalty/premium prices but have limited scale; mass markets offer scale but intense competition."]],
["Marketing mix",["7Ps: Product, Price, Promotion, Place, People, Process, Physical evidence.","Product portfolio tools include the Boston Matrix; product life cycle stages help guide promotion, investment and extension strategies.","Penetration pricing sets a relatively low launch price to build adoption; skimming uses a high initial price where willingness to pay is strong.","Promotion can include branding, social media and viral approaches.","Place includes multi-channel distribution; digital marketing/e-commerce can expand reach and data capture.","The mix must be integrated: one P can undermine another if positioning becomes inconsistent.","Boston Matrix: Stars, Cash Cows, Question Marks and Dogs help discuss portfolio balance, but labels depend on market-growth/share assumptions.","Product life cycle: introduction, growth, maturity and decline; extension strategies aim to prolong sales.","Digital marketing and e-commerce can widen reach, improve targeting/data and lower some distribution costs, but intensify price transparency and competition."]]
]},
operations:{name:"4. Operational Management",short:"Operations",subs:[
["Objectives & performance",["Operational objectives include cost, quality, speed, flexibility, environmental performance and added value.","Labour productivity = output ÷ number of employees (or labour input where specified).","Unit cost = total cost ÷ units produced.","Capacity is maximum possible output in a period.","Capacity utilisation = actual output ÷ maximum output × 100.","Very high utilisation can lower unit costs but leave little spare capacity for surges, maintenance or disruption."]],
["Efficiency, lean & technology",["Efficiency means achieving output with minimum wasted resources; productivity measures output per input.","Lean production removes waste; Just in Time minimises inventory, while Just in Case holds protection against disruption.","Capital-intensive production can improve consistency and output but requires investment and may reduce flexibility.","Labour-intensive production can offer flexibility/personal service but exposes the business to wage and skills pressures.","Technology can automate tasks, improve inventory visibility and link customers/suppliers."]],
["Quality, inventory & supply chain",["Quality control inspects output; quality assurance builds quality into processes.","Poor quality can cause rework, returns, lost reputation and lower repeat purchase.","Inventory choices depend on demand uncertainty, lead times, storage cost and supply risk.","Key inventory-chart ideas: buffer stock, reorder level, reorder quantity and lead time.","Businesses can match capacity to demand via outsourcing, temporary/part-time workers or producing to order.","Supplier choice should consider reliability, quality, price, flexibility, ethics and strategic risk.","Outsourcing can add specialist capability/flexibility but reduces direct control and creates supplier dependency.","Temporary/part-time labour and producing to order can help match capacity to demand, but may affect skills, consistency or speed."]]
]},
finance:{name:"5. Financial Management",short:"Finance",subs:[
["Objectives & profit",["Financial objectives include revenue, cost, profit, cash flow and return on investment targets. Return on investment asks whether the benefit earned justifies the capital committed.","Cash is money available to pay obligations; profit is revenue minus costs. A profitable firm can still run out of cash.","Gross profit = revenue − cost of sales.","Operating profit = gross profit − operating expenses.","Profit for the year accounts for the remaining finance/tax items relevant to the statement."]],
["Budgets, cash flow & break-even",["Budgets set planned income/costs; variance compares actual with budget. Whether a variance is favourable depends on what is being measured.","Cash-flow forecasts show timing of inflows and outflows and can expose shortages before they occur.","Contribution per unit = selling price − variable cost per unit.","Break-even output = fixed costs ÷ contribution per unit.","Margin of safety = actual/forecast output − break-even output.","Total contribution = contribution per unit × units sold (or total revenue − total variable costs).","Break-even is useful for scenarios but assumes simplified cost/revenue relationships."]],
["Profitability & finance",["Profit margins help compare profit relative to revenue; a rising absolute profit does not automatically mean better profitability.","Gross, operating and profit-for-the-year margins compare each profit measure with revenue × 100.","Receivables delay cash coming in; payables delay cash going out.","Internal finance includes retained profit; external sources include overdrafts, loans, share capital, venture capital, crowdfunding and factoring.","Short-term needs should not automatically be funded with long-term finance, and vice versa.","Choice depends on cost, risk, control, duration, cash-flow reliability and business form."]],
["Improving cash flow & profit",["Improve cash flow by accelerating inflows, delaying/controlling outflows, managing inventory or arranging appropriate finance.","Improve profit by increasing revenue, contribution, productivity or reducing avoidable costs.","A measure that improves cash today may damage long-term profit, supplier relations, quality or growth."]]
]},
hr:{name:"6. Human Resource Management",short:"HR",subs:[
["Objectives & performance",["HR objectives include engagement, talent development, training, diversity, values alignment and having the right number/skills/location of employees.","Hard HRM treats labour more as a cost/resource; soft HRM emphasises development, commitment and involvement.","Labour turnover measures employees leaving relative to the workforce.","Employee costs as % of turnover and labour cost per unit help assess workforce cost efficiency.","Low labour cost is not automatically good if quality, retention or customer service suffers."]],
["Structure & workforce flow",["Structures may be functional, product-based, regional or matrix.","Span of control, hierarchy, delegation, authority, centralisation and decentralisation shape speed, control and accountability.","Decentralisation can improve local responsiveness; centralisation can improve consistency and control.","HR planning anticipates workforce needs; flow includes recruitment, training, redeployment and redundancy."]],
["Motivation & engagement",["Taylor emphasises financial reward linked to output; Maslow presents a hierarchy of needs; Herzberg separates hygiene factors from motivators.","Maslow moves from basic/secure needs through social and esteem towards self-actualisation; the model is useful for thinking about different needs but people do not always follow a fixed sequence.","Financial methods include piece rate, commission, salary and performance-related pay.","Non-financial methods include empowerment, team working, flexible working, job enrichment and rotation.","Motivation methods must fit the task, employee needs, measurability and business culture."]],
["Employee relations",["Employee voice may involve trade unions, works councils and other consultation routes. Trade unions represent employee interests; works councils provide a formal employee-management consultation forum.","Good relations can improve trust, change adoption, retention and information flow.","Poor relations can increase conflict, disruption, turnover and reputational risk.","Evaluation: employee involvement can slow a decision but improve the probability of successful implementation."]]
]}
};
const formulas = [["Profit","Revenue − total costs"],["Revenue","Selling price × quantity sold"],["Total cost","Fixed costs + total variable costs"],["Market share","Business sales ÷ total market sales × 100"],["Market growth","Change in market size ÷ original market size × 100"],["Percentage change","Change ÷ original value × 100"],["Market capitalisation","Share price × number of issued shares"],["Labour productivity","Output ÷ labour input"],["Unit cost","Total cost ÷ units produced"],["Capacity utilisation","Actual output ÷ maximum output × 100"],["Contribution/unit","Selling price − variable cost/unit"],["Total contribution","Contribution/unit × units sold"],["Break-even output","Fixed costs ÷ contribution/unit"],["Margin of safety","Actual or forecast output − break-even output"],["Gross profit margin","Gross profit ÷ revenue × 100"],["Operating profit margin","Operating profit ÷ revenue × 100"],["Profit for year margin","Profit for year ÷ revenue × 100"],["Labour turnover","Leavers ÷ average number employed × 100"],["Employee cost % turnover","Employee costs ÷ turnover × 100"],["Labour cost/unit","Total labour cost ÷ units produced"],["Expected value","Σ (probability × outcome)"],["Net gain","Expected value − cost of decision"]];