const flashcards = [
["business","What is the difference between a mission and an objective?","A mission is the broad purpose/direction of the business. Objectives are specific targets used to pursue that mission."],
["business","Give three common business objectives.","Examples: survival, profit, growth, cash flow, market share, social/ethical objectives."],
["business","What is profit?","Revenue minus total costs."],
["business","Why can growth conflict with short-term profit?","Growth often requires investment, recruitment, marketing or capacity spending before extra revenue is earned."],
["business","What does limited liability mean?","Owners can generally lose the amount invested, rather than being personally liable for all business debts."],
["business","One advantage and one drawback of becoming a PLC?","Advantage: access to larger equity finance. Drawback: more disclosure/shareholder pressure and possible loss of control."],
["business","How can higher interest rates affect a business?","Borrowing becomes more expensive; consumers with debt may have less disposable income, potentially reducing demand."],
["business","Why might demographic change matter?","It can alter market size/segments, product needs, workforce availability and location decisions."],
["business","What is shareholder value?","The value delivered to shareholders through share-price gains and/or returns such as dividends."],
["business","Why might ethical sourcing raise both costs and demand?","It may increase input costs but strengthen reputation, differentiation and willingness to buy."],
["leadership","Name the four leadership styles required.","Autocratic, paternalistic, democratic and laissez-faire."],
["leadership","When might autocratic leadership be effective?","When decisions must be fast, control is critical, or employees need clear direction — but context matters."],
["leadership","When might democratic leadership improve performance?","When employee knowledge matters and involvement raises commitment, creativity or acceptance of change."],
["leadership","What does the Tannenbaum–Schmidt continuum show?","A range of leadership behaviour from manager-centred control towards greater subordinate freedom."],
["leadership","What is opportunity cost?","The value of the next best alternative given up by choosing one option."],
["leadership","Difference between risk and uncertainty?","Risk can be associated with estimable probabilities; uncertainty is harder or impossible to quantify reliably."],
["leadership","Expected value formula?","Sum of each possible outcome multiplied by its probability."],
["leadership","Why can a decision tree mislead?","The probabilities/outcomes are estimates and it can ignore qualitative factors, strategic fit and risk attitude."],
["leadership","What does a power–interest map help managers do?","Prioritise how closely stakeholders should be managed, informed or consulted."],
["leadership","Give one likely stakeholder conflict.","Employees may want higher pay while shareholders want lower costs/higher returns."],
["marketing","Primary vs secondary research?","Primary is collected first-hand for the current purpose; secondary already exists."],
["marketing","Qualitative vs quantitative research?","Qualitative explores reasons/opinions; quantitative produces numerical data."],
["marketing","Name three sampling methods.","Random, stratified and quota."],
["marketing","What does positive correlation mean?","As one variable increases, the other tends to increase. It does not prove that one causes the other."],
["marketing","What does price elasticity tell a manager?","How responsive demand is to a change in price, helping assess likely revenue/volume effects."],
["marketing","What is segmentation?","Dividing a market into groups with similar characteristics or behaviours."],
["marketing","Niche vs mass marketing?","Niche targets a narrow segment; mass targets a broad market. Trade-offs include scale, competition and specialisation."],
["marketing","What is market positioning?","How a product/brand is perceived relative to competitors in customers’ minds."],
["marketing","List the 7Ps.","Product, Price, Promotion, Place, People, Process, Physical evidence."],
["marketing","Penetration pricing vs skimming?","Penetration starts relatively low to build adoption; skimming starts high to capture customers with high willingness to pay."],
["marketing","What is an extension strategy?","Action intended to extend a product’s life cycle, e.g. repositioning, promotion, new use or product modification."],
["marketing","Why must the marketing mix be integrated?","The elements must reinforce the same target/positioning; inconsistent choices can confuse customers and waste spend."],
["operations","Capacity utilisation formula?","Actual output ÷ maximum possible output × 100."],
["operations","Why can 100% capacity utilisation be risky?","No spare capacity for demand surges, breakdowns, maintenance or supply problems; pressure may also harm quality."],
["operations","Labour productivity formula?","Output ÷ labour input (often output per employee in AS questions)."],
["operations","Unit cost formula?","Total cost ÷ number of units produced."],
["operations","JIT vs JIC?","JIT keeps minimal inventory and relies on timely supply; JIC holds more buffer inventory to protect against disruption."],
["operations","One benefit and one risk of JIT.","Benefit: lower inventory/storage/waste. Risk: disruption can stop production quickly."],
["operations","Quality control vs quality assurance?","Control checks finished/output items; assurance designs processes to prevent defects."],
["operations","Why can poor quality reduce profit beyond the cost of rework?","It can cause refunds, complaints, lower repeat purchase, reputation damage and weaker pricing power."],
["operations","What is a reorder level?","The inventory level that triggers a new order."],
["operations","What is lead time?","Time between placing an order and receiving it."],
["operations","Labour-intensive vs capital-intensive?","Labour-intensive relies more on people; capital-intensive relies more on machinery/technology."],
["operations","What factors matter when choosing a supplier?","Price, quality, reliability, lead time, flexibility, capacity, ethics and supply risk."],
["finance","Why is profit not the same as cash?","Profit records revenue/costs when earned/incurred; cash flow is the timing of money actually entering/leaving."],
["finance","Contribution per unit formula?","Selling price per unit − variable cost per unit."],
["finance","Break-even output formula?","Fixed costs ÷ contribution per unit."],
["finance","Margin of safety formula?","Actual or forecast output − break-even output."],
["finance","What is a favourable variance?","A difference from budget that improves the relevant financial outcome; whether it is favourable depends on the item."],
["finance","Why is a cash-flow forecast useful?","It identifies likely shortages/surpluses early so managers can change timing, finance or spending decisions."],
["finance","Gross profit formula?","Revenue − cost of sales."],
["finance","Gross profit margin formula?","Gross profit ÷ revenue × 100."],
["finance","Give three external sources of finance.","Examples: overdraft, loan, share capital, venture capital, crowdfunding, debt factoring."],
["finance","What is retained profit?","Profit kept in the business rather than distributed, used as internal finance."],
["finance","What is debt factoring?","Selling/assigning receivables to a factor to receive cash sooner, usually for a fee/discount."],
["finance","Why might cutting inventory improve cash but increase risk?","Less cash is tied up, but shortages can interrupt sales/production if demand or supply is uncertain."],
["hr","Hard HRM vs soft HRM?","Hard HRM emphasises labour as a cost/resource; soft HRM emphasises commitment, development and employee involvement."],
["hr","Labour turnover formula?","Number leaving ÷ average number employed × 100."],
["hr","Why might very low labour turnover not always be ideal?","It may indicate stability, but can also mean fewer new skills/ideas or poor movement if performance is weak."],
["hr","Name four organisational structures.","Functional, product-based, regional and matrix."],
["hr","What is span of control?","The number of subordinates directly reporting to a manager."],
["hr","Centralisation vs decentralisation?","Centralisation keeps decision authority near the top; decentralisation delegates more authority lower/down or locally."],
["hr","What does workforce planning do?","Forecasts the number, skills and location of employees needed and plans recruitment/training/redeployment/redundancy."],
["hr","Taylor’s main motivation idea?","Financial reward linked to output can motivate workers, especially in measurable repetitive work."],
["hr","Herzberg: hygiene factor vs motivator?","Hygiene factors prevent dissatisfaction; motivators such as achievement/responsibility can create satisfaction."],
["hr","Give four non-financial motivators.","Examples: empowerment, team working, flexible working, job enrichment, job rotation."],
["hr","Why can employee involvement make change more successful?","Employees contribute information, understand reasons, feel ownership and may resist less — though consultation takes time."],
["hr","Why can high turnover damage performance?","Recruitment/training cost rises; experience is lost; service/quality/productivity may fall while replacements learn."],
["business","Market capitalisation formula?","Share price × number of issued shares."],
["business","What is a dividend?","A payment made to shareholders from distributable profits. Paying more dividends leaves less retained profit for reinvestment."],
["business","Give two factors that can influence a share price.","Examples: expected future profit/cash flows, interest rates, economic outlook, competition, investor confidence and company-specific news."],
["marketing","What does a confidence interval tell a manager?","A range around an estimate reflecting uncertainty. A wider interval usually means less precision."],
["marketing","Name the four Boston Matrix categories.","Star, Cash Cow, Question Mark and Dog."],
["marketing","Name the main product life-cycle stages.","Introduction, growth, maturity and decline."],
["marketing","Give one advantage and one risk of e-commerce.","Advantage: wider reach/convenience/data. Risk: price transparency, cyber/fulfilment demands or stronger online competition."],
["operations","What is buffer inventory?","Extra inventory held above immediate expected need to protect against demand or supply uncertainty."],
["operations","Why might a business outsource?","To access specialist skills/capacity, lower cost or add flexibility; the trade-off is less direct control and supplier dependency."],
["operations","How can producing to order help operations?","It reduces finished-goods inventory and matches output to confirmed demand, but customers may wait longer."],
["finance","What does return on investment help a manager judge?","Whether the expected/actual benefit from an investment is worthwhile relative to the capital committed."],
["finance","Total contribution formula?","Contribution per unit × units sold, or total revenue − total variable costs."],
["finance","What are receivables and payables?","Receivables are amounts owed to the business by customers; payables are amounts the business owes suppliers/creditors."],
["hr","Employee costs as a percentage of turnover formula?","Employee costs ÷ turnover × 100."],
["hr","Labour cost per unit formula?","Total labour cost ÷ units produced."],
["hr","What is delegation?","Passing authority for a task/decision down the hierarchy while the manager retains ultimate accountability."],
["hr","Trade union vs works council?","A trade union represents employees and may negotiate collectively; a works council is a formal employee-management consultation body."]
];
const mindNodes = {
business:{"Objectives":"Objective changes alter finance, marketing, HR and operations priorities. Exam chain: growth objective → more investment/capacity → higher short-term cash need → source-of-finance decision.","Ownership":"Ownership affects access to finance, liability, control and objectives. Exam chain: LTD → limited private equity options → loan/retained profit more important → growth speed may be constrained.","External environment":"External changes hit demand/costs and force functional responses. Exam chain: interest rates rise → borrowing/customer spending pressure → demand or finance costs change → investment decision may be delayed."},
leadership:{"Leadership style":"Style affects speed, information quality and employee commitment. Democratic decision → more staff input → better local information/acceptance → implementation may improve, but decision takes longer.","Decision trees":"Quantifies uncertain choices, but assumptions matter. Higher expected value → looks attractive → yet if probabilities are weak or cash exposure is large → manager may rationally reject it.","Stakeholders":"A decision can create winners and losers. Wage rise → employees benefit → cost rises → shareholder return may fall unless productivity/retention improves."},
marketing:{"Research":"Better evidence can reduce decision risk. Research identifies a segment → targeted mix improves relevance → conversion/loyalty may rise → marketing spend becomes more productive.","Segmentation":"Target choice changes product, price, promotion and distribution. Niche target → tailored offer → differentiation/price premium → lower scale but stronger loyalty.","7Ps":"The mix links directly to finance and operations. Lower price → demand rises → capacity utilisation rises → unit costs may fall, but quality/capacity pressure may rise."},
operations:{"Capacity":"Capacity connects sales forecasts to cost and customer service. Demand growth → utilisation rises → unit cost may fall → but delays/quality failures can harm brand.","Lean/JIT":"Inventory decision connects cash flow to supply risk. JIT → less inventory cash tied up → improved cash flow → but supplier delay can stop output and sales.","Quality":"Quality links operations to marketing and finance. Assurance investment → fewer defects → lower returns + better reputation → repeat sales/margins may improve."},
finance:{"Cash flow":"Cash connects every decision. Rapid growth → more inventory/staff before receipts → cash outflows precede inflows → profitable growth can still create insolvency risk.","Break-even":"Break-even links price, cost and demand. Automation raises fixed cost but lowers variable cost → break-even may initially rise/fall depending on contribution → high-volume firms may benefit more.","Finance choice":"Funding affects risk/control. Equity → no scheduled loan repayment → cash pressure lower → but ownership/control diluted."},
hr:{"Motivation":"HR choices change operations and customer outcomes. Enrichment → higher engagement → productivity/quality may rise → unit cost or retention can improve.","Structure":"Structure changes decision speed/control. Decentralisation → local managers decide faster → better customer response → but inconsistent decisions may weaken brand/control.","Turnover":"Turnover links HR, cost and quality. High turnover → recruitment/training + inexperienced staff → cost rises/quality falls → profit and reputation can decline."}
};