(function(){
const ROOT='../../../../';
state.v2=state.v2||{examAttempts:[],examDrafts:{},diagnostics:[]};
state.v2.examAttempts=state.v2.examAttempts||[];state.v2.examDrafts=state.v2.examDrafts||{};state.v2.diagnostics=state.v2.diagnostics||[];

function addSpecCompletion(){
 const additions={
  business:[['Influences on business decisions',['Decisions are influenced by mission, objectives, ethics, resource constraints, stakeholder pressure, competition and the external environment.','A strong Paper 2 answer explains why the same factor can matter differently depending on the business context and objective.','Public-sector organisations are owned/controlled by government and may prioritise service, access or value for money rather than profit.','Shareholders may seek dividends and capital growth; their objectives can conflict with employees, customers or long-term reinvestment.','Fair trade and ethical choices can raise input costs but may improve reputation, differentiation and stakeholder trust.']]],
  marketing:[['Technology, relationships & pricing',['Relationship marketing aims to retain customers and increase lifetime value through ongoing engagement, service and personalised communication.','Dynamic pricing changes prices in response to factors such as demand, capacity, time or customer behaviour; it may improve revenue but can create fairness/reputation concerns.','Market mapping plots competing offers against two characteristics to identify positioning and possible gaps.','New product development can create growth and differentiation but carries research, development, launch and failure risk.','Income elasticity shows how demand responds to income changes; managers should interpret positive/negative values and relative responsiveness.']],['Integrated marketing mix',['The integrated mix must fit product type, target market, positioning, competition, marketing objectives, product life-cycle stage and portfolio position.','Changing one P can force changes elsewhere: a premium price needs a product, promotion, people/process and physical evidence that support the premium position.']]],
  operations:[['Inventory charts & improving performance',['Inventory-control charts can show buffer stock, reorder level, reorder quantity, maximum inventory and lead time.','Longer lead times or less reliable suppliers may justify a higher reorder level or buffer stock.','Productivity can improve through training, technology, better job design, lean methods and process redesign.','Efficiency improvements can reduce cost but may damage flexibility, quality, resilience or employee engagement if pushed too far.','When interpreting an operations graph, identify the trend/number first, then explain the business consequence.']]],
  finance:[['Constructing forecasts & charts',['A cash-flow forecast records expected cash inflows, cash outflows, net cash flow and opening/closing balances by period.','Closing balance = opening balance + net cash flow; a negative forecast balance signals a financing or timing problem.','Budgets set planned figures and variance analysis compares actual with budget; cost and revenue variances must be interpreted in context.','A break-even chart plots total revenue and total costs; their intersection is break-even output.','Higher fixed costs normally raise break-even; a higher selling price or lower variable cost raises contribution and normally lowers break-even, other things equal.']]],
  hr:[['Technology, labour markets & HR flow',['Technology can change required skills, job design, communication, monitoring and where work is performed, including remote working.','Labour-market conditions affect recruitment difficulty, wage pressure, retention and the bargaining power of employees.','Human-resource flow should be seen as a connected process: workforce plan → recruitment → training/development → redeployment or redundancy when needs change.','Remote working may widen recruitment and improve flexibility but can make coordination, culture, supervision or training harder.']]]
 };
 Object.entries(additions).forEach(([k,blocks])=>blocks.forEach(b=>{if(!topics[k].subs.some(s=>s[0]===b[0]))topics[k].subs.push(b)}));
 const extraCards=[
 ['business','Give four influences on a business decision.','Examples: mission/objectives, ethics, resources, stakeholder pressure, competition and external factors.'],
 ['business','How can shareholder objectives create a conflict?','Shareholders may want dividends/returns while managers may want to retain profit for investment or employees may want higher pay.'],
 ['business','Why may a public-sector organisation have different objectives?','It may prioritise service quality, access, coverage or value for money rather than shareholder profit.'],
 ['marketing','What is relationship marketing?','Building ongoing customer relationships to improve retention, loyalty and lifetime value.'],
 ['marketing','What is dynamic pricing?','Changing price in response to demand, capacity, time or other market/customer data.'],
 ['marketing','What is market mapping?','Plotting competing products/brands against two characteristics to understand positioning and identify potential gaps.'],
 ['marketing','Why is new product development risky?','Research/development and launch cost are committed before demand is certain; failure can waste cash and management time.'],
 ['marketing','What does positive income elasticity usually imply?','Demand tends to rise as consumer incomes rise; the size of the value indicates relative responsiveness.'],
 ['operations','What does a higher reorder level do?','It triggers replenishment earlier, offering more protection where lead time or usage uncertainty is high, but can increase average inventory.'],
 ['operations','How can productivity be improved?','Examples: training, technology, better processes/job design, lean methods, motivation and removing bottlenecks.'],
 ['operations','Why can maximum efficiency be dangerous?','Very lean resources may reduce spare capacity, resilience, flexibility, maintenance time or quality.'],
 ['finance','Cash-flow closing balance formula?','Opening balance + net cash flow = closing balance.'],
 ['finance','What happens to break-even if fixed costs rise?','Break-even output normally rises because more total contribution is needed to cover fixed costs.'],
 ['finance','What happens to break-even if contribution per unit rises?','Break-even output falls because each sale contributes more towards fixed costs.'],
 ['finance','What is an adverse variance?','A variance that worsens the relevant outcome versus budget, for example costs above budget or revenue below budget.'],
 ['hr','How can a tight labour market affect a business?','Recruitment may be harder and wages/benefits may need to rise, increasing cost and making retention more important.'],
 ['hr','Give the main stages of human-resource flow.','HR/workforce plan, recruitment, training/development, redeployment and redundancy as needs change.'],
 ['hr','One benefit and one risk of remote working?','Benefit: flexibility/wider recruitment or lower premises needs. Risk: coordination, culture, supervision, communication or training may weaken.']
 ];
 extraCards.forEach(c=>{if(!flashcards.some(x=>x[1]===c[1]))flashcards.push(c)});
 const extraQuestions=[
 {t:'marketing',q:'A hotel raises room prices automatically when occupancy reaches 90%. This is best described as:',o:['Market mapping','Dynamic pricing','Penetration pricing','Job enrichment'],a:1,e:'Dynamic pricing changes price as market/capacity conditions change.'},
 {t:'marketing',q:'Which action is most clearly relationship marketing?',o:['A one-off launch discount','A loyalty programme using purchase history to tailor offers','Closing a distribution channel','Increasing buffer inventory'],a:1,e:'Relationship marketing focuses on retention and the ongoing customer relationship.'},
 {t:'marketing',q:'If income rises by 5% and demand for a product rises by 10%, the product is relatively:',o:['Responsive to income changes','Completely unresponsive','Necessarily inferior','Price inelastic'],a:0,e:'Demand changed proportionately more than income, indicating relatively responsive positive income elasticity.'},
 {t:'operations',q:'A supplier lead time becomes less reliable. Which inventory response is most likely to improve resilience?',o:['Lower the reorder level','Remove buffer stock','Raise the reorder level or buffer stock','Guarantee JIT with zero stock'],a:2,e:'Earlier reordering/more buffer gives greater protection from uncertain delivery.'},
 {t:'operations',q:'Output rises from 12,000 to 13,800 units with the same 60 employees. Labour productivity rises by:',o:['3 units per employee','30 units per employee','23%','1800 employees'],a:1,e:'Productivity rises from 200 to 230 units per employee: an increase of 30.'},
 {t:'finance',q:'Opening cash balance is £8,000, inflows £27,000 and outflows £31,500. Closing balance is:',o:['£3,500','£11,500','−£4,500','£66,500'],a:0,e:'Net cash flow = −£4,500; £8,000 − £4,500 = £3,500 closing balance.'},
 {t:'finance',q:'Which change would normally reduce break-even output?',o:['Higher fixed costs','Lower contribution per unit','Higher contribution per unit','Higher rent with no other change'],a:2,e:'Break-even = fixed costs ÷ contribution per unit, so a larger contribution lowers break-even.'},
 {t:'finance',q:'Budgeted revenue is £240,000 and actual revenue is £228,000. The revenue variance is:',o:['£12,000 favourable','£12,000 adverse','£468,000 adverse','5% favourable'],a:1,e:'Actual revenue is £12,000 below budget, so the revenue variance is adverse.'},
 {t:'hr',q:'A tight labour market is most likely to cause:',o:['Easier recruitment at lower wages','Greater wage and retention pressure','Guaranteed lower labour turnover','No effect on HR decisions'],a:1,e:'Scarce suitable labour can make recruitment harder and increase wage/retention pressure.'},
 {t:'hr',q:'Which sequence best represents human-resource flow?',o:['Redundancy → recruitment → no planning','HR plan → recruitment → training → redeployment/redundancy as needs change','Pricing → promotion → recruitment','JIT → training → market mapping'],a:1,e:'AQA expects HR flow to include planning, recruitment, training, redeployment and redundancy.'},
 {t:'business',q:'Which objective is most likely to be especially important to a public-sector service?',o:['Dividend growth only','Service access and value for money','Share-price maximisation','Venture-capital exit'],a:1,e:'Public-sector organisations may prioritise service provision and value for money rather than shareholder returns.'}
 ];
 extraQuestions.forEach(q=>{if(!questions.some(x=>x.q===q.q))questions.push(q)});
}
addSpecCompletion();

const DATA_DRILLS=[
 ['Index numbers','A market index rises from 100 to 118 while a business sales index rises from 100 to 109. What does this suggest?','The market has grown faster than the business. The business may have lost relative market share even though its own sales increased.'],
 ['Cash-flow forecast','Opening balance £5,000; inflows £24,000; outflows £31,000. Calculate the closing balance and interpret it.','Closing balance = £5,000 + £24,000 − £31,000 = −£2,000. The business forecasts a cash shortage and needs to change timing/spending or arrange finance.'],
 ['Break-even change','Fixed costs rise from £80,000 to £100,000 while contribution stays £10 per unit. What happens to break-even?','It rises from 8,000 units to 10,000 units. The business must sell 2,000 more units before total contribution covers fixed costs.'],
 ['Inventory chart','A supplier lead time increases from 5 to 9 days while usage remains similar. What inventory control change may be sensible?','Reorder earlier (raise the reorder level) and/or hold a larger buffer, because stock must last longer before replenishment arrives.'],
 ['Market data','Market size grows 12% but a firm’s sales grow 4%. What is the likely market-share direction?','Down. The business is growing more slowly than the overall market, so its share is likely to fall.'],
 ['Productivity','A business makes 18,000 units with 90 employees, then 21,000 with 84 employees. Compare productivity.','It rises from 200 to 250 units per employee. This is a 25% productivity improvement, which may reduce labour cost per unit if labour cost does not rise too much.'],
 ['Margin interpretation','Gross margin rises while operating margin falls. Give one plausible explanation.','Direct/product costs improved relative to revenue, but operating expenses such as marketing, salaries, rent or administration rose enough to reduce operating profitability.'],
 ['Correlation','A scatter graph shows strong positive correlation between advertising and sales. What can a manager conclude?','There is a strong association, but not proof that advertising caused the sales increase; other variables may explain both.']
];

const SIMULATORS=[{
 id:'harbour-home-1',title:'Harbour Home Ltd',subtitle:'Full original Paper 2 simulation',
 caseHtml:`<p>Harbour Home Ltd (HH) is a UK private limited company selling modular home-office furniture online. It was founded six years ago by Maya and Ben, who each own 50% of the shares. Revenue has grown rapidly as hybrid working has become common, but management is now concerned that growth is creating operational and financial pressure.</p>
 <p>HH manufactures desks and storage units in a rented factory. In 2025 it sold 18,000 units. The average selling price was £180, total variable costs were £1.89m and fixed costs were £720,000. In 2026 maximum annual capacity is 24,000 units and forecast output is 22,800 units. Customer reviews remain strong overall, but complaints about late delivery have doubled.</p>
 <p>HH currently holds significant timber and component inventory because one key supplier has a long and unreliable lead time. The operations director proposes investing £500,000 in automated cutting equipment. She predicts this would increase capacity by 20%, reduce waste and lower variable cost per unit. Some experienced production employees fear the equipment will reduce job security. Labour turnover has already risen from 8% to 15%.</p>
 <p>The marketing director wants to launch a premium range aimed at professional designers. Research suggests the segment values customisation and sustainable materials more than low prices. She proposes a high initial price and a relationship-marketing programme for repeat trade customers. Competitors are also entering the premium segment.</p>
 <p>HH forecasts a temporary cash deficit if it buys the equipment immediately. A bank has offered a five-year loan. An investor has offered the full £500,000 in exchange for 20% of HH and a board seat. Maya prefers to retain control; Ben believes the investor’s e-commerce experience could accelerate growth.</p>
 <p><strong>Industry data:</strong> the UK home-office furniture market index is 100 in 2024, 111 in 2025 and 123 in 2026. HH sales index is 100 in 2024, 119 in 2025 and 128 in 2026.</p>`,
 questions:[
  {marks:3,topic:'business',ao:{ao1:1,ao2:2},q:'Using the index data, calculate the percentage increase in the UK home-office furniture market between 2024 and 2026.',guide:['Use the index change: (123 − 100) ÷ 100 × 100.','Correct answer: 23%.','Show the method and include %.']},
  {marks:3,topic:'finance',ao:{ao1:1,ao2:2},q:'Using the 2025 data, calculate HH’s total contribution.',guide:['Revenue = 18,000 × £180 = £3,240,000.','Total contribution = total revenue − total variable costs.','Correct answer: £1,350,000.']},
  {marks:4,topic:'operations',ao:{ao1:2,ao2:2},q:'Explain one benefit to HH of operating at its forecast 2026 capacity utilisation.',guide:['Capacity utilisation = 22,800 ÷ 24,000 × 100 = 95%.','Explain one contextual benefit such as spreading fixed costs across more output or making strong use of factory resources.','Apply to HH’s growth/cost position; do not claim high utilisation has no drawbacks.']},
  {marks:9,topic:'operations',ao:{ao1:3,ao2:3,ao3:3},q:'Analyse the impact on HH of holding significant inventory.',guide:['Develop at least one benefit and/or drawback with HH context.','Possible benefit: protects production from the unreliable supplier/long lead time, reducing lost output and late deliveries.','Possible drawback: cash is tied up, storage/waste risk rises and this matters because HH already forecasts a cash deficit.','Push the chain through to competitiveness, customer service, cash flow or profit.']},
  {marks:9,topic:'marketing',ao:{ao1:3,ao2:3,ao3:3},q:'Analyse the impact on HH of using a high initial price for the premium range.',guide:['Recognise price skimming/high initial pricing.','Use the designer segment’s stated preference for customisation/sustainable materials and potential willingness to pay.','Analyse revenue/margin/positioning benefits, but also competitor entry and volume risk.','A developed contextual chain matters more than listing advantages.']},
  {marks:16,topic:'hr',ao:{ao1:4,ao2:2,ao3:4,ao4:6},q:'To what extent should HH use a more democratic approach when implementing the automation project?',guide:['Analyse why employee involvement may improve information, acceptance, retention and implementation.','Use labour turnover rising 8% → 15% and job-security fears.','Counterbalance with speed, management expertise and the need to make a £500,000 investment decision.','Judgement should state what degree of consultation is appropriate and what it depends on.']},
  {marks:16,topic:'finance',ao:{ao1:4,ao2:4,ao3:4,ao4:4},q:'Do you think HH should use the bank loan or the investor to finance the automation? Justify your answer.',guide:['Analyse both options rather than giving isolated pros/cons.','Loan preserves Maya/Ben’s control but creates interest/repayment pressure while cash is forecast to be tight.','Investor reduces scheduled repayment pressure and brings e-commerce experience, but gives up 20% ownership and a board seat.','Make a contextual judgement based on cash resilience, control objectives, cost of finance and strategic value of expertise.']},
  {marks:20,topic:'marketing',ao:{ao1:4,ao2:3,ao3:5,ao4:8},q:'“For a growing business such as HH, operational performance is more important than marketing performance in determining long-term success.” To what extent do you agree?',guide:['This is synoptic: draw together operations, marketing, finance and HR where relevant.','Operations case: 95% utilisation, late deliveries, supplier risk, automation, quality/capacity and cost.','Marketing case: premium positioning, new segment, competition, relationship marketing and willingness to pay.','Evaluate interdependence: strong marketing can create demand operations cannot fulfil; strong operations without demand cannot create sustainable revenue.','Finish with a clear, conditional judgement about which constraint is currently most important for HH and why long-term priorities may change.']}
 ]
}];

function injectV2(){
 const style=document.createElement('style');style.textContent=`
 .v2-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.v2-metric{background:white;border:1px solid var(--line);border-radius:16px;padding:17px}.v2-metric strong{display:block;font-size:27px;letter-spacing:-.03em}.v2-metric span{font-size:12px;color:var(--muted)}.focus-list{display:grid;gap:9px}.focus-item{display:flex;gap:12px;align-items:center;padding:12px;border:1px solid var(--line);border-radius:12px;background:#fff}.focus-rank{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:var(--navy);color:white;font-weight:800}.focus-item .grow{flex:1}.status-chip{display:inline-block;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:800;background:#eef2f5}.status-chip.weak{background:#fff0f1;color:#9f2f38}.status-chip.dev{background:#fff7e8;color:#94600b}.status-chip.secure{background:#e8f7f0;color:#0b784b}.ao-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.ao-card{padding:16px;border:1px solid var(--line);border-radius:14px;background:white}.ao-card b{display:block;font-size:23px}.exam-shell{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:16px}.exam-side{position:sticky;top:18px;align-self:start}.timer{font-size:30px;font-weight:900;letter-spacing:-.04em}.exam-question{margin:14px 0}.exam-question textarea{width:100%;min-height:150px;border:1px solid var(--line);border-radius:12px;padding:13px;resize:vertical;background:white}.marks{float:right;color:var(--muted);font-size:13px}.mark-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:10px 0}.mark-grid label{font-size:11px;color:var(--muted)}.mark-grid input{width:100%;padding:8px;border:1px solid var(--line);border-radius:8px}.mark-answer{white-space:pre-wrap;background:#f7f9fb;border-radius:10px;padding:12px;margin:8px 0;color:#405062}.data-drill{margin:10px 0}.data-drill summary{cursor:pointer;font-weight:800}.history-row{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid var(--line);padding:9px 0}.home-focus{margin:18px 0 0}@media(max-width:900px){.v2-metrics,.ao-grid{grid-template-columns:repeat(2,1fr)}.exam-shell{grid-template-columns:1fr}.exam-side{position:static}}@media(max-width:560px){.v2-metrics,.ao-grid{grid-template-columns:1fr}.mark-grid{grid-template-columns:repeat(2,1fr)}}`;
 document.head.appendChild(style);
 const nav=document.getElementById('nav');
 if(!document.querySelector('#nav [data-v="progress"]'))nav.insertAdjacentHTML('beforeend',`<button data-v="progress" onclick="showView('progress');renderProgressV2()">Progress</button><button data-v="exam" onclick="showView('exam');renderExamLandingV2()">Exam</button>`);
 const mobile=document.getElementById('mobileNav');
 if(!document.getElementById('v2MobileProgress'))mobile.insertAdjacentHTML('beforeend',`<button id="v2MobileProgress" onclick="showView('progress');renderProgressV2()">Progress</button><button onclick="showView('exam');renderExamLandingV2()">Exam</button>`);
 document.querySelector('main').insertAdjacentHTML('beforeend',`<section class="view" id="progress"><div class="eyebrow">Measured readiness</div><h1 class="title">Progress & focus</h1><p class="subtitle">Scores combine recall, testing and exam evidence. Low evidence is shown separately so a high score from one easy question is not mistaken for mastery.</p><div id="progressBody"></div></section><section class="view" id="exam"><div id="examBody"></div></section>`);
 const home=document.getElementById('home');if(home&&!document.getElementById('homeFocusV2'))home.querySelector('.hero').insertAdjacentHTML('afterend','<div id="homeFocusV2" class="card home-focus"></div>');
 const test=document.getElementById('test');const filters=test.querySelector('.filters');filters.insertAdjacentHTML('beforeend','<button class="pill" id="dataTab" onclick="setTestMode(\'data\')">Data lab</button>');test.insertAdjacentHTML('beforeend','<div id="dataLab" style="display:none"></div>');
 renderDataLabV2();
}

function cardStats(k){const ids=flashcards.map((c,i)=>[c,i]).filter(x=>x[0][0]===k).map(x=>x[1]);const seen=ids.filter(i=>state.cards[i]);const score=seen.length?seen.reduce((s,i)=>s+(state.cards[i].score||0),0)/(seen.length*2)*100:null;return{score,coverage:ids.length?seen.length/ids.length:0,seen:seen.length,total:ids.length}}
function quizStats(k){const rows=Object.entries(state.quiz).filter(([i])=>questions[i]&&questions[i].t===k);return{score:rows.length?rows.filter(x=>x[1]===1).length/rows.length*100:null,count:rows.length}}
function recentExamRows(){return(state.v2.examAttempts||[]).slice(-3)}
function examTopicStats(k){let got=0,max=0;recentExamRows().forEach(a=>{got+=a.topic?.[k]||0;max+=a.topicMax?.[k]||0});return{score:max?got/max*100:null,max}}
function topicV2(k){const c=cardStats(k),q=quizStats(k),e=examTopicStats(k);let weighted=0,w=0;if(c.score!==null){weighted+=c.score*0.4;w+=0.4}if(q.score!==null){weighted+=q.score*0.25;w+=0.25}if(e.score!==null){weighted+=e.score*0.35;w+=0.35}const raw=w?weighted/w:0;const confidence=Math.min(1,c.coverage*.4+Math.min(1,q.count/3)*.25+(e.max?0.35:0));const adjusted=Math.round(raw*(.55+.45*confidence));return{raw:Math.round(raw),adjusted,confidence,c,q,e}}
function overallV2(){const vals=Object.keys(topics).map(topicV2);return Math.round(vals.reduce((s,x)=>s+x.adjusted,0)/vals.length)}
function statusFor(v,conf){if(conf<.08)return['Not assessed',''];if(v<50)return['Needs work','weak'];if(v<70)return['Developing','dev'];if(v<85)return['Secure','secure'];return['Strong','secure']}
function aoStats(){const attempts=recentExamRows();const max={ao1:0,ao2:0,ao3:0,ao4:0},got={ao1:0,ao2:0,ao3:0,ao4:0};attempts.forEach(a=>Object.keys(max).forEach(k=>{max[k]+=a.aoMax?.[k]||0;got[k]+=a.ao?.[k]||0}));return Object.fromEntries(Object.keys(max).map(k=>[k,{score:max[k]?Math.round(got[k]/max[k]*100):null,got:got[k],max:max[k]}]))}
function focusAreas(){return Object.keys(topics).map(k=>({k,...topicV2(k)})).sort((a,b)=>a.adjusted-b.adjusted||a.confidence-b.confidence).slice(0,3)}
function recommendation(x){if(x.c.coverage<.45)return`Build recall coverage: ${x.c.seen}/${x.c.total} flashcards assessed.`;if(x.q.score===null||x.q.score<65)return'Use a targeted mixed test and repair any missed concepts.';if(x.e.score===null)return'Knowledge evidence exists; now prove it in case-study exam questions.';if(x.e.score<65)return'Case-study marks are the constraint: practise application, analysis and judgement.';return'Retest this area to confirm it remains secure.'}

function renderProgressV2(){
 const body=document.getElementById('progressBody');if(!body)return;const overall=overallV2(),fs=focusAreas(),ao=aoStats();const conf=Math.round(Object.keys(topics).reduce((s,k)=>s+topicV2(k).confidence,0)/Object.keys(topics).length*100);const attempts=state.v2.examAttempts||[];
 body.innerHTML=`<div class="v2-metrics"><div class="v2-metric"><strong>${overall}%</strong><span>Readiness score</span></div><div class="v2-metric"><strong>${conf}%</strong><span>Evidence confidence</span></div><div class="v2-metric"><strong>${Object.values(state.cards).filter(Boolean).length}</strong><span>Flashcards assessed</span></div><div class="v2-metric"><strong>${attempts.length}</strong><span>Full exam attempts</span></div></div>
 <div class="card"><h2 style="margin-top:0">What to focus on next</h2><div class="focus-list">${fs.map((x,i)=>{const st=statusFor(x.adjusted,x.confidence);return`<div class="focus-item"><span class="focus-rank">${i+1}</span><div class="grow"><b>${topics[x.k].name}</b><div class="small">${recommendation(x)}</div></div><span class="status-chip ${st[1]}">${st[0]} · ${x.adjusted}%</span></div>`}).join('')}</div></div>
 <h2 style="margin-top:24px">Topic readiness</h2><div class="grid6">${Object.keys(topics).map(k=>{const x=topicV2(k),st=statusFor(x.adjusted,x.confidence);return`<div class="card"><div class="topic-head"><h3>${topics[k].short}</h3><b>${x.confidence<.08?'—':x.adjusted+'%'}</b></div><div class="bar"><i style="width:${x.adjusted}%"></i></div><div class="small">Evidence ${Math.round(x.confidence*100)}% · Recall ${x.c.score===null?'—':Math.round(x.c.score)+'%'} · Quiz ${x.q.score===null?'—':Math.round(x.q.score)+'%'} · Exam ${x.e.score===null?'—':Math.round(x.e.score)+'%'}</div></div>`}).join('')}</div>
 <h2 style="margin-top:24px">Exam skills</h2><div class="ao-grid">${[['ao1','AO1 Knowledge'],['ao2','AO2 Application'],['ao3','AO3 Analysis'],['ao4','AO4 Evaluation']].map(([k,n])=>`<div class="ao-card"><span class="small">${n}</span><b>${ao[k].score===null?'Not assessed':ao[k].score+'%'}</b><span class="small">${ao[k].max?ao[k].got+' / '+ao[k].max+' recent exam marks':'Complete a full simulator to measure this skill.'}</span></div>`).join('')}</div>
 <div class="card" style="margin-top:18px"><h2 style="margin-top:0">Exam history</h2>${attempts.length?attempts.slice().reverse().map(a=>`<div class="history-row"><span><b>${a.title}</b><br><span class="small">${new Date(a.date).toLocaleDateString()}</span></span><b>${a.score}/80 · ${Math.round(a.score/80*100)}%</b></div>`).join(''):'<p>No full Paper 2 attempt yet. The simulator gives the strongest evidence of readiness because it measures application, analysis and evaluation as well as recall.</p>'}<button class="cta" onclick="showView('exam');renderExamLandingV2()">Open exam simulator</button></div>`;
 updateHomeV2();
}
function updateHomeV2(){const box=document.getElementById('homeFocusV2');if(!box)return;const overall=overallV2(),fs=focusAreas();box.innerHTML=`<div class="eyebrow">Your focus</div><h2 style="margin:5px 0 8px">${overall}% measured readiness</h2><p>${fs.map((x,i)=>`${i+1}. ${topics[x.k].short}: ${recommendation(x)}`).join('<br>')}</p><button class="cta secondary" onclick="showView('progress');renderProgressV2()">See full progress</button> <button class="cta" onclick="showView('exam');renderExamLandingV2()">Paper 2 simulator</button>`;const el=document.getElementById('readiness');if(el)el.textContent=overall+'%';const ring=document.getElementById('ring');if(ring)ring.style.setProperty('--pct',overall+'%');const status=document.getElementById('statusLine');if(status)status.textContent=overall<40?'Build knowledge + evidence':overall<60?'Develop application':overall<75?'Push analysis and judgement':overall<88?'Exam-ready work':'Strong measured readiness';const next=document.getElementById('nextText');if(next)next.textContent=`Priority: ${topics[fs[0].k].short}. ${recommendation(fs[0])}`}

function renderDataLabV2(){const el=document.getElementById('dataLab');if(!el)return;el.innerHTML=`<div class="card"><div class="eyebrow">Quantitative & graphical thinking</div><h2>Data lab</h2><p>Do the calculation or interpretation before opening the answer. AQA can assess quantitative skills across assessment objectives, so the final sentence should explain what the number means for the business.</p>${DATA_DRILLS.map((d,i)=>`<details class="learn-section data-drill"><summary>${i+1}. ${d[0]} — ${d[1]}</summary><div class="callout" style="margin-top:10px">${d[2]}</div></details>`).join('')}</div>`}
const oldSetTestMode=setTestMode;setTestMode=function(m){const data=document.getElementById('dataLab');const tab=document.getElementById('dataTab');if(m==='data'){document.getElementById('quickTest').style.display='none';document.getElementById('caseTest').style.display='none';data.style.display='block';document.getElementById('quickTab').classList.remove('active');document.getElementById('caseTab').classList.remove('active');tab.classList.add('active');renderDataLabV2();return}data.style.display='none';tab.classList.remove('active');oldSetTestMode(m)};

let diagnosticActive=false;const oldRenderQuestion=renderQuestion;renderQuestion=function(){if(testPos>=testList.length&&diagnosticActive){state.v2.diagnostics.push({date:new Date().toISOString(),score:testScore,max:testList.length,questions:[...testList]});diagnosticActive=false;save()}oldRenderQuestion()};
startDiagnostic=function(){showView('test');setTestMode('quick');testStarted=true;testScore=0;testPos=0;answered=false;diagnosticActive=true;testList=Object.keys(topics).flatMap(k=>{const pool=questions.map((q,i)=>q.t===k?i:null).filter(i=>i!==null).sort(()=>Math.random()-.5);return pool.slice(0,3)});renderQuestion()};

let examTimer=null;
function renderExamLandingV2(){clearInterval(examTimer);const el=document.getElementById('examBody');if(!el)return;const sim=SIMULATORS[0],draft=state.v2.examDrafts[sim.id];el.innerHTML=`<div class="eyebrow">Paper 2 simulator</div><h1 class="title">90 minutes. 80 marks. One case.</h1><p class="subtitle">This simulator mirrors a real recent AQA Paper 2 mark profile: 3, 3, 4, 9, 9, 16, 16 and 20 marks. The case and questions here are original.</p><div class="hero"><div class="card"><h2>${sim.title}</h2><p>${sim.subtitle}</p><div class="chain"><span>2 calculations</span><span>1 explain</span><span>2 analyse</span><span>2 × 16-mark judgement</span><span>20-mark synoptic</span></div><button class="cta" onclick="startExamV2(true)">${draft?'Resume timed attempt':'Start 90-minute exam'}</button> <button class="cta secondary" onclick="startExamV2(false)">Practice untimed</button></div><div class="card"><h3>How results feed progress</h3><p>After the paper, use the guided self-marking screen. Marks are recorded by AO1–AO4 and topic, so Progress can identify whether the problem is knowledge, application, analysis or evaluation — and which subject area needs work.</p></div></div>`}
function startExamV2(timed){const sim=SIMULATORS[0];let d=state.v2.examDrafts[sim.id];if(!d||d.finished){d={mode:timed?'timed':'practice',startedAt:Date.now(),deadline:timed?Date.now()+90*60*1000:null,answers:{},finished:false};state.v2.examDrafts[sim.id]=d;save()}renderExamPaperV2(sim,d)}
function renderExamPaperV2(sim,d){clearInterval(examTimer);const el=document.getElementById('examBody');el.innerHTML=`<div class="exam-shell"><div><div class="eyebrow">${d.mode==='timed'?'Timed Paper 2':'Practice Paper 2'}</div><h1 class="title">${sim.title}</h1><div class="card case-text">${sim.caseHtml}</div>${sim.questions.map((q,i)=>`<div class="card exam-question"><span class="marks">[${q.marks} marks]</span><h3>${i+1}. ${q.q}</h3><textarea id="examAns${i}" oninput="draftAnswerV2(${i},this.value)" placeholder="Write your answer here...">${escapeHtml(d.answers[i]||'')}</textarea></div>`).join('')}<button class="cta" onclick="finishExamV2()">Finish paper & mark it</button></div><aside class="card exam-side"><div class="eyebrow">Time</div><div class="timer" id="examTimer">${d.mode==='timed'?'90:00':'Untimed'}</div><p class="small">80 marks total. Move on if a question is consuming disproportionate time.</p><div class="bar"><i id="examProgress" style="width:0%"></i></div><div class="small" id="examProgressText">0 / 8 answers started</div><button class="cta secondary" style="margin-top:12px" onclick="renderExamLandingV2()">Leave & save draft</button></aside></div>`;updateExamProgressV2();if(d.mode==='timed'){tickExamV2();examTimer=setInterval(tickExamV2,1000)}}
function escapeHtml(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
let draftSaveTimer=null;function draftAnswerV2(i,v){const sim=SIMULATORS[0],d=state.v2.examDrafts[sim.id];d.answers[i]=v;updateExamProgressV2();clearTimeout(draftSaveTimer);draftSaveTimer=setTimeout(save,900)}
function updateExamProgressV2(){const d=state.v2.examDrafts[SIMULATORS[0].id];if(!d)return;const n=Object.values(d.answers).filter(x=>String(x).trim()).length;const bar=document.getElementById('examProgress'),txt=document.getElementById('examProgressText');if(bar)bar.style.width=(n/8*100)+'%';if(txt)txt.textContent=`${n} / 8 answers started`}
function tickExamV2(){const d=state.v2.examDrafts[SIMULATORS[0].id],el=document.getElementById('examTimer');if(!d||!el)return;const left=Math.max(0,d.deadline-Date.now()),m=Math.floor(left/60000),s=Math.floor(left%60000/1000);el.textContent=`${m}:${String(s).padStart(2,'0')}`;if(left<=0){clearInterval(examTimer);finishExamV2(true)}}
function finishExamV2(auto=false){if(!auto&&!confirm('Finish the paper and move to marking? You will no longer edit these answers in this attempt.'))return;clearInterval(examTimer);const sim=SIMULATORS[0],d=state.v2.examDrafts[sim.id];d.finished=true;d.finishedAt=Date.now();save();renderMarkingV2(sim,d)}
function renderMarkingV2(sim,d){const el=document.getElementById('examBody');el.innerHTML=`<div class="eyebrow">Guided self-marking</div><h1 class="title">Mark the paper by assessment objective</h1><p class="subtitle">Use a best-fit approach: reward what is present, then enter marks up to the AO maximum shown. This turns the paper into diagnostic evidence rather than just a total score.</p>${sim.questions.map((q,i)=>`<div class="card exam-question"><span class="marks">[${q.marks} marks]</span><h3>${i+1}. ${q.q}</h3><div class="small">Your answer</div><div class="mark-answer">${escapeHtml(d.answers[i]||'(No answer)')}</div><details class="learn-section"><summary>Open marking guidance</summary><ul>${q.guide.map(g=>`<li>${g}</li>`).join('')}</ul></details><div class="mark-grid">${Object.entries(q.ao).map(([ao,max])=>`<label>${ao.toUpperCase()} / ${max}<input id="mark-${i}-${ao}" type="number" min="0" max="${max}" value="0"></label>`).join('')}</div></div>`).join('')}<button class="cta" onclick="saveExamMarksV2()">Save marks & analyse weaknesses</button>`}
function saveExamMarksV2(){const sim=SIMULATORS[0],d=state.v2.examDrafts[sim.id];const ao={ao1:0,ao2:0,ao3:0,ao4:0},aoMax={ao1:0,ao2:0,ao3:0,ao4:0},topic={},topicMax={};let total=0;sim.questions.forEach((q,i)=>{let qScore=0;Object.entries(q.ao).forEach(([k,max])=>{const el=document.getElementById(`mark-${i}-${k}`);let v=Math.max(0,Math.min(max,Number(el?.value||0)));ao[k]+=v;aoMax[k]+=max;qScore+=v});total+=qScore;topic[q.topic]=(topic[q.topic]||0)+qScore;topicMax[q.topic]=(topicMax[q.topic]||0)+q.marks});state.v2.examAttempts.push({id:sim.id,title:sim.title,date:new Date().toISOString(),score:total,max:80,ao,aoMax,topic,topicMax,duration:Math.round(((d.finishedAt||Date.now())-d.startedAt)/60000)});delete state.v2.examDrafts[sim.id];save();showView('progress');renderProgressV2()}

injectV2();renderLearn();buildFlashOrder();renderProgressV2();renderExamLandingV2();
const legacyDashboard=renderDashboard;renderDashboard=function(){legacyDashboard();renderProgressV2()};
window.renderProgressV2=renderProgressV2;window.renderExamLandingV2=renderExamLandingV2;window.startExamV2=startExamV2;window.draftAnswerV2=draftAnswerV2;window.finishExamV2=finishExamV2;window.saveExamMarksV2=saveExamMarksV2;
})();